# -*- coding: utf-8 -*-
"""Lote 1 - 30 comidas/cenas (intercambiables). Pesos de carne/pescado/cereal en CRUDO.
Legumbres en cocido/conserva; verduras en crudo salvo indicacion."""

def _r(id, nombre, dif, t, ings, pasos):
    return {"id": id, "nombre": nombre, "tipo": "comida_cena", "dificultad": dif,
            "tiempo_min": t, "raciones": 1,
            "ingredientes": [{"f_id": f, "nombre": nm, "gramos": g, "casera": c} for f, nm, g, c in ings],
            "elaboracion": pasos}

RECETAS = [
 _r("C001","Pollo a la plancha con arroz integral y brocoli","facil",30,
    [("994","Pechuga de pollo",150,"1 filete"),("56","Arroz integral",70,"1 vaso pequeño en crudo"),
     ("312","Brocoli",150,"1/2 arbol"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece el arroz integral en agua con sal unos 20 min y escurre.",
     "Hierve o cuece al vapor el brocoli 6-8 min.",
     "Haz el pollo a la plancha con la mitad del aceite, salpimentado.",
     "Sirve todo junto y aliña con el resto del aceite."]),
 _r("C002","Merluza al horno con patata y judias verdes","facil",35,
    [("2347","Merluza fresca",180,"1 rodaja"),("2403","Patata",150,"1 mediana"),
     ("2397","Judia verde",120,"2 puñados"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Corta la patata en rodajas finas y hornea 15 min a 200 grados con un poco de aceite.",
     "Añade la merluza y hornea otros 12 min.",
     "Cuece las judias verdes 10 min y sirvelas de guarnicion."]),
 _r("C003","Lentejas guisadas con verduras","facil",40,
    [("1324","Lentejas cocidas",200,"1 plato"),("1773","Cebolla",40,"1/4"),("1892","Zanahoria",50,"1/2"),
     ("1894","Pimiento rojo",40,"1/4"),("1879","Tomate",60,"1/2"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Pocha la cebolla, zanahoria y pimiento troceados en el aceite.",
     "Añade el tomate rallado y sofrie.",
     "Incorpora las lentejas cocidas, cubre con un poco de agua y guisa 10 min."]),
 _r("C004","Salmon a la plancha con quinoa y esparragos","facil",25,
    [("2626","Salmon",150,"1 lomo"),("1083","Quinoa",60,"1/2 vaso en crudo"),
     ("151","Esparrago verde",100,"1 manojo"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la quinoa 15 min y escurre.",
     "Saltea los esparragos con parte del aceite.",
     "Marca el salmon a la plancha 3-4 min por lado y sirve."]),
 _r("C005","Pasta integral con atun y tomate","facil",20,
    [("1364","Pasta",80,"1 plato en crudo"),("2131","Atun en aceite (escurrido)",80,"1 lata"),
     ("1879","Tomate",100,"1 unidad"),("1773","Cebolla",30,"1/4"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la pasta segun el paquete y escurre.",
     "Sofrie la cebolla y el tomate rallado en el aceite.",
     "Añade el atun escurrido y mezcla con la pasta."]),
 _r("C006","Ternera salteada con verduras y arroz","media",30,
    [("304","Lomo de vacuno",150,"1 filete"),("56","Arroz integral",70,"1 vaso pequeño en crudo"),
     ("1894","Pimiento rojo",60,"1/2"),("2376","Calabacin",80,"1/2"),("1773","Cebolla",40,"1/4"),
     ("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece el arroz y escurre.",
     "Saltea a fuego fuerte la cebolla, pimiento y calabacin en tiras.",
     "Añade la ternera en tiras, saltea 3-4 min y sirve con el arroz."]),
 _r("C007","Garbanzos con espinacas","facil",25,
    [("1292","Garbanzos cocidos",200,"1 plato"),("2395","Espinacas",150,"2 puñados"),
     ("1774","Ajo",5,"1 diente"),("1879","Tomate",60,"1/2"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Dora el ajo laminado en el aceite.",
     "Añade el tomate rallado y las espinacas hasta que reduzcan.",
     "Incorpora los garbanzos, salpimenta y calienta 5 min."]),
 _r("C008","Tortilla de patata y cebolla con ensalada","media",35,
    [("2127","Huevo",120,"2 unidades"),("2403","Patata",150,"1 mediana"),("1773","Cebolla",50,"1/2"),
     ("1775","Lechuga",40,"unas hojas"),("1879","Tomate",60,"1/2"),("2544","Aceite de oliva virgen extra",15,"1,5 cucharadas")],
    ["Frie la patata y cebolla en laminas a fuego medio hasta que esten blandas.",
     "Bate los huevos, mezcla y cuaja la tortilla por ambos lados.",
     "Acompaña con la ensalada de lechuga y tomate aliñada."]),
 _r("C009","Pavo a la plancha con pure de patata y zanahoria","facil",30,
    [("1371","Pechuga de pavo",150,"1 filete"),("2403","Patata",150,"1 mediana"),
     ("1892","Zanahoria",80,"1 unidad"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la patata y la zanahoria y machacalas con un poco de aceite.",
     "Haz el pavo a la plancha salpimentado.",
     "Sirve el pavo sobre el pure."]),
 _r("C010","Bacalao con pimientos y ajo","media",25,
    [("1915","Bacalao",180,"1 lomo"),("1894","Pimiento rojo",100,"1 unidad"),
     ("1774","Ajo",5,"1 diente"),("2544","Aceite de oliva virgen extra",12,"1 cucharada")],
    ["Asa los pimientos en tiras con parte del aceite.",
     "Dora el ajo laminado.",
     "Cocina el bacalao a fuego suave 8 min y sirve con los pimientos."]),
 _r("C011","Arroz con pollo y verduras","facil",30,
    [("56","Arroz integral",75,"1 vaso pequeño en crudo"),("994","Pechuga de pollo",130,"1 filete"),
     ("1892","Zanahoria",50,"1/2"),("1894","Pimiento rojo",50,"1/2"),("1773","Cebolla",40,"1/4"),
     ("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Sofrie la verdura troceada en el aceite.",
     "Añade el pollo en dados y dora.",
     "Incorpora el arroz y agua (doble volumen) y cuece 18 min."]),
 _r("C012","Ensalada de garbanzos, atun y huevo","facil",15,
    [("1292","Garbanzos cocidos",150,"1 plato"),("2131","Atun en aceite (escurrido)",60,"1/2 lata"),
     ("2126","Huevo cocido",60,"1 unidad"),("1879","Tomate",80,"1/2"),("1775","Lechuga",40,"unas hojas"),
     ("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Mezcla los garbanzos con la lechuga y el tomate troceados.",
     "Añade el atun escurrido y el huevo cocido en cuartos.",
     "Aliña con el aceite y una pizca de sal."]),
 _r("C013","Lomo de cerdo a la plancha con pimientos y patata","facil",30,
    [("2259","Lomo de cerdo",150,"1 filete"),("1894","Pimiento rojo",100,"1 unidad"),
     ("2403","Patata",150,"1 mediana"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece o asa la patata.",
     "Asa los pimientos en tiras.",
     "Haz el lomo a la plancha y sirve con las guarniciones."]),
 _r("C014","Sepia a la plancha con ensalada","facil",20,
    [("1854","Sepia",200,"1 unidad"),("1775","Lechuga",50,"unas hojas"),("1879","Tomate",80,"1/2"),
     ("1773","Cebolla",30,"1/4"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Haz la sepia a la plancha fuerte con parte del aceite y ajo si quieres.",
     "Prepara la ensalada de lechuga, tomate y cebolla.",
     "Aliña y sirve junto a la sepia."]),
 _r("C015","Wok de tofu con verduras y arroz","media",25,
    [("1121","Tofu",150,"1/2 bloque"),("56","Arroz integral",70,"1 vaso pequeño en crudo"),
     ("2376","Calabacin",80,"1/2"),("1892","Zanahoria",60,"1/2"),("1894","Pimiento rojo",60,"1/2"),
     ("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece el arroz y reserva.",
     "Saltea el tofu en dados hasta dorar y reserva.",
     "Saltea la verdura en juliana, incorpora el tofu y el arroz y mezcla."]),
 _r("C016","Sardinas al horno con ensalada de tomate","facil",20,
    [("2630","Sardina",150,"3-4 unidades"),("1879","Tomate",120,"1 unidad"),("1773","Cebolla",30,"1/4"),
     ("2544","Aceite de oliva virgen extra",8,"1 cucharada"),("2163","Pan integral",40,"1 rebanada")],
    ["Hornea las sardinas 10 min a 200 grados.",
     "Prepara la ensalada de tomate y cebolla aliñada.",
     "Acompaña con el pan."]),
 _r("C017","Crema de calabacin con huevo cocido","facil",25,
    [("2376","Calabacin",250,"1 unidad grande"),("2403","Patata",60,"1/2 pequeña"),("1773","Cebolla",40,"1/4"),
     ("2126","Huevo cocido",60,"1 unidad"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece el calabacin, la patata y la cebolla 20 min.",
     "Tritura con un poco del agua y el aceite hasta crema.",
     "Sirve con el huevo cocido troceado por encima."]),
 _r("C018","Alubias blancas con verduras","facil",25,
    [("898","Alubias blancas cocidas",200,"1 plato"),("1892","Zanahoria",50,"1/2"),("1773","Cebolla",40,"1/4"),
     ("1894","Pimiento rojo",40,"1/4"),("1879","Tomate",60,"1/2"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Pocha la cebolla, zanahoria y pimiento en el aceite.",
     "Añade el tomate rallado.",
     "Incorpora las alubias, cubre con caldo y guisa 10 min."]),
 _r("C019","Muslo de pollo asado con patata","facil",45,
    [("1388","Muslo de pollo",180,"1 unidad"),("2403","Patata",150,"1 mediana"),("1773","Cebolla",40,"1/4"),
     ("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Coloca el muslo, la patata en gajos y la cebolla en una bandeja.",
     "Riega con el aceite, salpimenta y asa 35 min a 200 grados."]),
 _r("C020","Ensalada de pasta con pavo y verduras","facil",20,
    [("1364","Pasta",80,"1 plato en crudo"),("1699","Pavo fiambre",60,"3 lonchas"),("1879","Tomate",80,"1/2"),
     ("1772","Pepino",60,"1/4"),("1894","Pimiento rojo",40,"1/4"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la pasta, escurre y enfria.",
     "Trocea el pavo y las verduras.",
     "Mezcla todo y aliña con el aceite."]),
 _r("C021","Mejillones al vapor con ensalada","facil",20,
    [("2345","Mejillon",200,"1 plato"),("1775","Lechuga",50,"unas hojas"),("1879","Tomate",80,"1/2"),
     ("1773","Cebolla",30,"1/4"),("2544","Aceite de oliva virgen extra",8,"1 cucharada"),("2163","Pan integral",40,"1 rebanada")],
    ["Abre los mejillones al vapor con un poco de agua y limon.",
     "Prepara una ensalada sencilla.",
     "Sirve los mejillones con la ensalada y el pan."]),
 _r("C022","Quinoa con verduras salteadas y huevo","facil",25,
    [("1083","Quinoa",70,"1/2 vaso en crudo"),("2376","Calabacin",80,"1/2"),("1894","Pimiento rojo",60,"1/2"),
     ("1773","Cebolla",40,"1/4"),("2127","Huevo",60,"1 unidad"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la quinoa 15 min.",
     "Saltea la verdura en dados.",
     "Mezcla con la quinoa y corona con un huevo a la plancha."]),
 _r("C023","Gambas al ajillo con arroz","facil",20,
    [("2337","Gambas",150,"1 plato"),("56","Arroz integral",70,"1 vaso pequeño en crudo"),
     ("1774","Ajo",6,"1-2 dientes"),("2544","Aceite de oliva virgen extra",12,"1 cucharada")],
    ["Cuece el arroz.",
     "Dora el ajo laminado en el aceite.",
     "Saltea las gambas 2-3 min y sirve sobre el arroz."]),
 _r("C024","Solomillo de cerdo con pure y champiñones","media",30,
    [("447","Solomillo de cerdo",150,"1 unidad"),("2403","Patata",150,"1 mediana"),
     ("2384","Champiñon",100,"5-6 unidades"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la patata y haz un pure.",
     "Saltea los champiñones laminados.",
     "Marca el solomillo en medallones y sirve con pure y champiñones."]),
 _r("C025","Ensalada completa de pollo, aguacate y huevo","facil",20,
    [("994","Pechuga de pollo",130,"1 filete"),("1623","Aguacate",60,"1/2"),("2126","Huevo cocido",60,"1 unidad"),
     ("1775","Lechuga",50,"unas hojas"),("1879","Tomate",80,"1/2"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Haz el pollo a la plancha y trocealo.",
     "Monta la ensalada con lechuga, tomate, aguacate y huevo.",
     "Añade el pollo y aliña."]),
 _r("C026","Berenjena rellena de ternera","media",45,
    [("1921","Berenjena",200,"1 unidad"),("1931","Carne picada de vacuno",120,"1 puñado"),("1879","Tomate",80,"1/2"),
     ("1773","Cebolla",40,"1/4"),("1901","Queso curado",20,"para gratinar"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Asa la berenjena 20 min y retira la pulpa.",
     "Sofrie cebolla, pulpa y carne con el tomate.",
     "Rellena, cubre con queso y gratina 8 min."]),
 _r("C027","Coliflor gratinada con pavo","facil",30,
    [("2387","Coliflor",200,"1 plato"),("1371","Pechuga de pavo",120,"1 filete"),
     ("1901","Queso curado",25,"para gratinar"),("2544","Aceite de oliva virgen extra",8,"1 cucharada")],
    ["Cuece la coliflor 12 min.",
     "Saltea el pavo en dados.",
     "Coloca en fuente, cubre con queso y gratina."]),
 _r("C028","Bonito con pisto de verduras","media",35,
    [("800","Bonito",150,"1 rodaja"),("2376","Calabacin",80,"1/2"),("1894","Pimiento rojo",60,"1/2"),
     ("1879","Tomate",100,"1 unidad"),("1773","Cebolla",40,"1/4"),("2544","Aceite de oliva virgen extra",12,"1 cucharada")],
    ["Sofrie cebolla, pimiento y calabacin en dados.",
     "Añade el tomate y cocina el pisto 15 min.",
     "Marca el bonito a la plancha y sirve sobre el pisto."]),
 _r("C029","Pasta con champiñones y pollo","facil",25,
    [("1364","Pasta",80,"1 plato en crudo"),("994","Pechuga de pollo",120,"1 filete"),
     ("2384","Champiñon",100,"5-6 unidades"),("1774","Ajo",5,"1 diente"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la pasta.",
     "Saltea el ajo, el pollo en dados y los champiñones.",
     "Mezcla con la pasta y sirve."]),
 _r("C030","Acelgas rehogadas con patata y huevo","facil",25,
    [("1922","Acelga",200,"2 puñados"),("2403","Patata",150,"1 mediana"),("2126","Huevo cocido",60,"1 unidad"),
     ("1774","Ajo",5,"1 diente"),("2544","Aceite de oliva virgen extra",10,"1 cucharada")],
    ["Cuece la acelga y la patata troceadas 15 min y escurre.",
     "Rehoga con el ajo laminado en el aceite.",
     "Sirve con el huevo cocido en cuartos."]),
]
