# -*- coding: utf-8 -*-
"""20 recetas de hamburguesas (tipo comida_cena). Ingredientes por f_id de BEDCA.
Pesos de carne/pollo/pavo/pescado en crudo; pan tipo hamburguesa ~80 g/unidad."""

def _r(id, nombre, dif, t, ings, pasos):
    return {"id": id, "nombre": nombre, "tipo": "comida_cena", "dificultad": dif,
            "tiempo_min": t, "raciones": 1,
            "ingredientes": [{"f_id": f, "nombre": nm, "gramos": g, "casera": c} for f, nm, g, c in ings],
            "elaboracion": pasos}

# atajos de ingredientes comunes
PAN = ("2174", "Pan de hamburguesa", 80, "1 unidad")
LECHUGA = ("1775", "Lechuga", 20, "1 hoja")
TOMATE = ("1879", "Tomate", 40, "2 rodajas")
CEBOLLA = ("1773", "Cebolla", 20, "unos aros")

RECETAS = [
 _r("H001", "Hamburguesa clasica de ternera", "facil", 20,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), LECHUGA, TOMATE, CEBOLLA,
     ("1842", "Ketchup", 15, "1 cucharada")],
    ["Forma la hamburguesa con la carne, salpimenta y hazla a la plancha 3-4 min por lado.",
     "Tuesta ligeramente el pan.",
     "Monta con lechuga, tomate, cebolla, la carne y el ketchup."]),
 _r("H002", "Hamburguesa con queso (cheeseburger)", "facil", 20,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("1901", "Queso curado", 25, "1 loncha"),
     LECHUGA, TOMATE, ("1842", "Ketchup", 12, "1 cucharada")],
    ["Haz la hamburguesa a la plancha.",
     "Cuando le des la vuelta, pon el queso encima para que funda.",
     "Monta el pan con lechuga, tomate y la carne con queso."]),
 _r("H003", "Hamburguesa con queso y bacon", "facil", 22,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("1901", "Queso curado", 25, "1 loncha"),
     ("602", "Bacon", 20, "2 tiras"), LECHUGA, TOMATE],
    ["Dora el bacon en la plancha y reserva.",
     "Haz la hamburguesa y funde el queso encima.",
     "Monta con lechuga, tomate, la carne con queso y el bacon."]),
 _r("H004", "Hamburguesa doble de ternera con queso", "media", 25,
    [PAN, ("1931", "Carne picada de ternera", 200, "2 hamburguesas finas"), ("1901", "Queso curado", 30, "2 lonchas"),
     ("1773", "Cebolla", 25, "unos aros"), ("1842", "Ketchup", 12, "1 cucharada")],
    ["Forma dos hamburguesas finas y hazlas a la plancha.",
     "Funde una loncha de queso sobre cada una.",
     "Apila las dos con la cebolla y el ketchup en el pan."]),
 _r("H005", "Hamburguesa de pollo a la plancha", "facil", 20,
    [PAN, ("994", "Pechuga de pollo", 130, "1 filete"), LECHUGA, TOMATE,
     ("2554", "Mayonesa ligera", 15, "1 cucharada")],
    ["Haz la pechuga a la plancha, salpimentada.",
     "Tuesta el pan y unta la mayonesa.",
     "Monta con lechuga, tomate y el pollo."]),
 _r("H006", "Hamburguesa de pollo con queso y aguacate", "facil", 22,
    [PAN, ("994", "Pechuga de pollo", 130, "1 filete"), ("2510", "Queso mozzarella", 25, "1 loncha"),
     ("1623", "Aguacate", 40, "1/4"), LECHUGA],
    ["Haz el pollo a la plancha y funde el queso encima.",
     "Machaca el aguacate y untalo en el pan.",
     "Monta con la lechuga y el pollo con queso."]),
 _r("H007", "Hamburguesa de pavo con aguacate", "facil", 20,
    [PAN, ("1371", "Pechuga de pavo", 130, "1 filete"), ("1623", "Aguacate", 45, "1/4"), LECHUGA, TOMATE],
    ["Forma la hamburguesa de pavo y hazla a la plancha.",
     "Unta el aguacate machacado en el pan.",
     "Monta con lechuga, tomate y el pavo."]),
 _r("H008", "Hamburguesa de tofu (vegana)", "facil", 20,
    [PAN, ("1121", "Tofu", 120, "1 filete"), ("1623", "Aguacate", 40, "1/4"), LECHUGA, TOMATE,
     ("1773", "Cebolla", 20, "unos aros")],
    ["Corta el tofu en filete, marínalo si quieres y dóralo a la plancha.",
     "Unta el aguacate en el pan.",
     "Monta con lechuga, tomate, cebolla y el tofu."]),
 _r("H009", "Hamburguesa de lentejas (vegetariana)", "media", 30,
    [PAN, ("1126", "Lentejas cocidas", 150, "para la masa"), ("2127", "Huevo", 30, "1/2, para ligar"),
     LECHUGA, TOMATE, ("2554", "Mayonesa ligera", 12, "1 cucharada")],
    ["Tritura las lentejas con el huevo y especias y forma una hamburguesa.",
     "Dórala a la plancha por ambos lados con cuidado.",
     "Monta el pan con mayonesa, lechuga, tomate y la hamburguesa."]),
 _r("H010", "Hamburguesa de salmon", "media", 22,
    [PAN, ("2626", "Salmon", 130, "1 lomo"), ("1623", "Aguacate", 40, "1/4"), LECHUGA,
     ("2554", "Mayonesa ligera", 12, "1 cucharada")],
    ["Pica o desmenuza el salmón, forma la hamburguesa y hazla a la plancha.",
     "Unta la mayonesa y el aguacate en el pan.",
     "Monta con lechuga y el salmón."]),
 _r("H011", "Hamburguesa de atun", "facil", 20,
    [PAN, ("2134", "Atun fresco", 130, "1 rodaja"), LECHUGA, TOMATE, ("1773", "Cebolla", 20, "unos aros"),
     ("2554", "Mayonesa ligera", 12, "1 cucharada")],
    ["Marca el atún a la plancha vuelta y vuelta.",
     "Unta la mayonesa en el pan.",
     "Monta con lechuga, tomate, cebolla y el atún."]),
 _r("H012", "Hamburguesa de ternera con huevo frito", "facil", 22,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("545", "Huevo frito", 60, "1 unidad"),
     LECHUGA, TOMATE],
    ["Haz la hamburguesa a la plancha.",
     "Fríe un huevo aparte.",
     "Monta con lechuga, tomate, la carne y el huevo frito encima."]),
 _r("H013", "Hamburguesa de ternera con aguacate", "facil", 20,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("1623", "Aguacate", 45, "1/4"),
     LECHUGA, TOMATE],
    ["Haz la hamburguesa a la plancha.",
     "Machaca el aguacate y untalo en el pan.",
     "Monta con lechuga, tomate y la carne."]),
 _r("H014", "Hamburguesa de ternera con champiñones", "media", 25,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("2384", "Champiñones", 60, "un puñado"),
     ("1901", "Queso curado", 20, "1 loncha"), LECHUGA],
    ["Saltea los champiñones laminados.",
     "Haz la hamburguesa y funde el queso encima.",
     "Monta con lechuga, la carne con queso y los champiñones."]),
 _r("H015", "Hamburguesa BBQ de ternera con cebolla", "facil", 22,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("1979", "Cebolla caramelizada", 30, "unos aros"),
     ("1901", "Queso curado", 20, "1 loncha"), ("1842", "Salsa (ketchup/BBQ)", 15, "1 cucharada")],
    ["Pocha la cebolla a fuego lento hasta caramelizar.",
     "Haz la hamburguesa y funde el queso.",
     "Monta con la salsa, la carne con queso y la cebolla."]),
 _r("H016", "Hamburguesa mexicana con aguacate", "media", 24,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("1623", "Aguacate", 40, "1/4"),
     ("1894", "Pimiento rojo", 40, "unas tiras"), ("1773", "Cebolla", 20, "unos aros"), LECHUGA],
    ["Saltea el pimiento y la cebolla en tiras.",
     "Haz la hamburguesa a la plancha.",
     "Monta con aguacate, lechuga, la carne y las verduras."]),
 _r("H017", "Hamburguesa de pollo con queso y bacon", "facil", 22,
    [PAN, ("994", "Pechuga de pollo", 130, "1 filete"), ("1901", "Queso curado", 25, "1 loncha"),
     ("602", "Bacon", 20, "2 tiras"), LECHUGA, TOMATE],
    ["Dora el bacon y reserva.",
     "Haz el pollo a la plancha y funde el queso encima.",
     "Monta con lechuga, tomate, el pollo con queso y el bacon."]),
 _r("H018", "Hamburguesa vegetal de tofu con champiñones", "media", 24,
    [PAN, ("1121", "Tofu", 120, "1 filete"), ("2384", "Champiñones", 60, "un puñado"),
     ("1623", "Aguacate", 40, "1/4"), LECHUGA],
    ["Dora el tofu en filete a la plancha.",
     "Saltea los champiñones.",
     "Monta el pan con aguacate, lechuga, el tofu y los champiñones."]),
 _r("H019", "Hamburguesa de ternera con queso curado y pepinillos", "facil", 20,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("1901", "Queso curado", 25, "1 loncha"),
     ("2406", "Pepinillos", 15, "unas rodajas"), ("1798", "Mostaza", 10, "1 cucharadita"), LECHUGA],
    ["Haz la hamburguesa a la plancha y funde el queso.",
     "Unta la mostaza en el pan.",
     "Monta con lechuga, la carne con queso y los pepinillos."]),
 _r("H020", "Hamburguesa completa (ternera, queso, bacon y huevo)", "media", 25,
    [PAN, ("1931", "Carne picada de ternera", 130, "1 hamburguesa"), ("1901", "Queso curado", 25, "1 loncha"),
     ("602", "Bacon", 20, "2 tiras"), ("545", "Huevo frito", 60, "1 unidad"), LECHUGA, TOMATE],
    ["Dora el bacon y fríe el huevo.",
     "Haz la hamburguesa y funde el queso encima.",
     "Monta con lechuga, tomate, la carne con queso, el bacon y el huevo."]),
]
