# -*- coding: utf-8 -*-
"""Lote 3 - 100 recetas mas (25 desayunos + 50 comidas/cenas + 25 meriendas).
Ingredientes por CLAVE canonica (ver ingredientes.py)."""

def R(id, nombre, tipo, dif, t, ings, pasos):
    return {"id": id, "nombre": nombre, "tipo": tipo, "dificultad": dif, "tiempo_min": t,
            "raciones": 1, "_ings_clave": ings, "elaboracion": pasos}

RECETAS = [
 # ============ DESAYUNOS (25) ============
 R("D201","Tostada de pan de centeno con tomate y queso fresco","desayuno","facil",6,
   [("pan_centeno",60,"2 rebanadas"),("tomate",70,"1/2"),("queso_fresco",50,"unas lonchas"),("aceite_oliva",5,"1/2 cucharada")],
   ["Tuesta el pan.","Añade el tomate, el queso y un hilo de aceite."]),
 R("D202","Bowl de avena con manzana, nueces y canela","desayuno","facil",8,
   [("avena",50,"5 cucharadas"),("leche_semi",200,"1 vaso"),("manzana",100,"1 pequeña"),("nuez",15,"2 nueces"),("canela",1,"1 pizca")],
   ["Mezcla la avena con la leche.","Añade la manzana, las nueces y la canela."]),
 R("D203","Tortilla de 2 huevos con espinacas y queso","desayuno","facil",10,
   [("huevo",120,"2 unidades"),("espinaca",70,"1 puñado"),("queso_fresco",30,"un poco"),("aceite_oliva",8,"1 cucharada")],
   ["Saltea las espinacas.","Añade los huevos batidos con el queso y cuaja la tortilla."]),
 R("D204","Yogur griego con granola y arandanos","desayuno","facil",4,
   [("yogur_griego",125,"1 unidad"),("muesli",35,"3 cucharadas"),("arandano",70,"un puñado")],
   ["Mezcla el yogur con el muesli.","Añade los arandanos."]),
 R("D205","Tostada de crema de cacahuete y fresas","desayuno","facil",5,
   [("pan_integral",60,"2 rebanadas"),("crema_cacahuete",20,"1 cucharada"),("fresa",80,"5 unidades")],
   ["Tuesta el pan.","Unta la crema y añade las fresas."]),
 R("D206","Batido de yogur, mango y avena","desayuno","facil",5,
   [("yogur_natural",125,"1 unidad"),("mango",120,"1/2"),("avena",25,"2 cucharadas"),("leche_semi",100,"medio vaso")],
   ["Tritura todos los ingredientes."]),
 R("D207","Huevos a la plancha con pan y aguacate","desayuno","facil",10,
   [("huevo",120,"2 unidades"),("pan_integral",40,"1 rebanada"),("aguacate",60,"1/2"),("aceite_oliva",8,"1 cucharada")],
   ["Haz los huevos a la plancha.","Sirve con el pan y el aguacate."]),
 R("D208","Porridge de avena con pera y nueces","desayuno","facil",10,
   [("avena",50,"5 cucharadas"),("leche_semi",200,"1 vaso"),("pera",100,"1 pequeña"),("nuez",15,"2 nueces")],
   ["Cuece la avena con la leche.","Añade la pera troceada y las nueces."]),
 R("D209","Bowl de yogur con kiwi, platano y semillas","desayuno","facil",5,
   [("yogur_natural",125,"1 unidad"),("kiwi",70,"1 unidad"),("platano",80,"1/2"),("almendra",15,"un puñado")],
   ["Pon el yogur en un bol.","Añade la fruta troceada y las almendras."]),
 R("D210","Tostada de requeson, higos y miel","desayuno","facil",5,
   [("pan_integral",60,"2 rebanadas"),("requeson",70,"unas cucharadas"),("higo",60,"1 unidad"),("miel",8,"1 cucharadita")],
   ["Tuesta el pan.","Unta el requeson, añade los higos y la miel."]),
 R("D211","Revuelto de claras con champiñones y pavo","desayuno","facil",10,
   [("clara",120,"4 claras"),("champinon",70,"3 unidades"),("pavo_fiambre",40,"2 lonchas"),("aceite_oliva",6,"1/2 cucharada"),("pan_integral",40,"1 rebanada")],
   ["Saltea los champiñones y el pavo.","Añade las claras y cuaja.","Sirve con el pan."]),
 R("D212","Batido de leche, cacao y platano","desayuno","facil",5,
   [("leche_semi",250,"1 vaso grande"),("chocolate_negro",10,"1 onza"),("platano",100,"1 unidad"),("avena",20,"2 cucharadas")],
   ["Tritura todos los ingredientes."]),
 R("D213","Tostada de pan integral con pavo y tomate","desayuno","facil",6,
   [("pan_integral",60,"2 rebanadas"),("pavo_fiambre",40,"2 lonchas"),("tomate",60,"1/2"),("aceite_oliva",5,"1/2 cucharada")],
   ["Tuesta el pan.","Añade el tomate, el pavo y un hilo de aceite."]),
 R("D214","Yogur griego con melocoton y almendras","desayuno","facil",4,
   [("yogur_griego",125,"1 unidad"),("melocoton",120,"1 unidad"),("almendra",15,"un puñado"),("miel",8,"1 cucharadita")],
   ["Pon el yogur en un bol.","Añade el melocoton troceado, las almendras y la miel."]),
 R("D215","Tortitas de avena con arandanos","desayuno","facil",15,
   [("avena",50,"5 cucharadas"),("huevo",60,"1 unidad"),("leche_semi",50,"un chorro"),("arandano",60,"un puñado")],
   ["Tritura la avena con el huevo y la leche.","Haz tortitas y sirve con los arandanos."]),
 R("D216","Pan de centeno con aguacate y salmon","desayuno","media",8,
   [("pan_centeno",60,"2 rebanadas"),("aguacate",50,"1/3"),("salmon",50,"unas lonchas")],
   ["Tuesta el pan.","Unta el aguacate y coloca el salmon."]),
 R("D217","Bowl de fruta con requeson y nueces","desayuno","facil",6,
   [("requeson",125,"1 tarrina"),("manzana",80,"1/2"),("naranja",100,"1 pequeña"),("nuez",15,"2 nueces")],
   ["Pon el requeson en un bol.","Añade la fruta troceada y las nueces."]),
 R("D218","Porridge de quinoa con platano y canela","desayuno","facil",20,
   [("quinoa",50,"1/2 vaso"),("leche_semi",200,"1 vaso"),("platano",100,"1 unidad"),("canela",1,"1 pizca")],
   ["Cuece la quinoa con la leche.","Añade el platano y la canela."]),
 R("D219","Tostada de tomate, aceite y queso fresco","desayuno","facil",5,
   [("pan_integral",60,"2 rebanadas"),("tomate",70,"1/2"),("aceite_oliva",8,"1 cucharada"),("queso_fresco",40,"unas lonchas")],
   ["Tuesta el pan y unta el tomate con el aceite.","Coloca el queso."]),
 R("D220","Batido verde de espinaca, manzana y pera","desayuno","facil",5,
   [("espinaca",40,"1 puñado"),("manzana",100,"1 pequeña"),("pera",100,"1 pequeña"),("leche_semi",150,"1 vaso")],
   ["Tritura todos los ingredientes."]),
 R("D221","Yogur natural con datiles, avena y canela","desayuno","facil",4,
   [("yogur_natural",125,"1 unidad"),("datil",25,"2 unidades"),("avena",25,"2 cucharadas"),("canela",1,"1 pizca")],
   ["Mezcla el yogur con la avena.","Añade los datiles troceados y la canela."]),
 R("D222","Huevo cocido con pan de centeno y tomate","desayuno","facil",12,
   [("huevo_cocido",60,"1 unidad"),("pan_centeno",60,"2 rebanadas"),("tomate",70,"1/2"),("aceite_oliva",5,"1/2 cucharada")],
   ["Cuece el huevo.","Sirve con el pan, el tomate y un hilo de aceite."]),
 R("D223","Tostada de platano, crema de cacahuete y canela","desayuno","facil",5,
   [("pan_integral",60,"2 rebanadas"),("crema_cacahuete",20,"1 cucharada"),("platano",90,"1 unidad"),("canela",1,"1 pizca")],
   ["Tuesta el pan.","Unta la crema, añade el platano y la canela."]),
 R("D224","Bowl de yogur griego con cerezas y pistachos","desayuno","facil",5,
   [("yogur_griego",125,"1 unidad"),("cereza",90,"un puñado"),("pistacho",15,"un puñado"),("miel",8,"1 cucharadita")],
   ["Pon el yogur en un bol.","Añade las cerezas, los pistachos y la miel."]),
 R("D225","Tortilla francesa con jamon cocido y pan","desayuno","facil",10,
   [("huevo",120,"2 unidades"),("jamon_cocido",40,"2 lonchas"),("aceite_oliva",6,"1/2 cucharada"),("pan_integral",40,"1 rebanada")],
   ["Bate los huevos con el jamon troceado.","Cuaja la tortilla y sirve con el pan."]),

 # ============ COMIDAS / CENAS (50) ============
 R("C201","Pechuga de pollo con boniato y esparragos","comida_cena","facil",30,
   [("pollo_pechuga",150,"1 filete"),("boniato",150,"1 unidad"),("esparrago",100,"1 manojo"),("aceite_oliva",10,"1 cucharada")],
   ["Asa el boniato.","Saltea los esparragos.","Haz el pollo a la plancha y sirve."]),
 R("C202","Salmon con patata y judias verdes","comida_cena","facil",30,
   [("salmon",150,"1 lomo"),("patata",150,"1 mediana"),("judia_verde",120,"2 puñados"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata y las judias.","Marca el salmon a la plancha y sirve."]),
 R("C203","Dorada al horno con verduras","comida_cena","facil",30,
   [("dorada",180,"1 unidad"),("calabacin",80,"1/2"),("pimiento",60,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Hornea las verduras en juliana 15 min.","Añade la dorada y hornea 12 min."]),
 R("C204","Garbanzos salteados con verduras y arroz","comida_cena","facil",25,
   [("garbanzo_cocido",160,"1 plato"),("arroz_blanco",40,"en crudo"),("pimiento",50,"1/2"),("calabacin",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea las verduras y los garbanzos.","Mezcla con el arroz."]),
 R("C205","Pavo con pure de patata y guisantes","comida_cena","facil",30,
   [("pavo_pechuga",150,"1 filete"),("patata",150,"1 mediana"),("guisante",70,"2 cucharadas"),("aceite_oliva",10,"1 cucharada")],
   ["Haz un pure con la patata.","Cuece los guisantes.","Haz el pavo a la plancha y sirve."]),
 R("C206","Bacalao con garbanzos y espinacas","comida_cena","media",30,
   [("bacalao",160,"1 lomo"),("garbanzo_cocido",150,"1 plato"),("espinaca",120,"2 puñados"),("aceite_oliva",10,"1 cucharada")],
   ["Rehoga las espinacas.","Añade los garbanzos y el bacalao desmigado.","Guisa 8 min."]),
 R("C207","Ternera con pure de calabaza y arroz","comida_cena","media",30,
   [("vacuno_solomillo",150,"1 filete"),("calabaza",180,"1 taza"),("arroz_integral",60,"en crudo"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Haz un pure con la calabaza.","Marca la ternera y sirve."]),
 R("C208","Lubina con quinoa y calabacin","comida_cena","facil",25,
   [("lubina",180,"1 unidad"),("quinoa",60,"1/2 vaso"),("calabacin",100,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa.","Saltea el calabacin.","Haz la lubina a la plancha y sirve."]),
 R("C209","Pollo al curry ligero con arroz","comida_cena","media",30,
   [("pollo_pechuga",150,"1 filete"),("arroz_blanco",70,"en crudo"),("cebolla",50,"1/2"),("leche_semi",50,"un chorro"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Sofrie la cebolla, añade el pollo y un poco de leche.","Sirve con el arroz."]),
 R("C210","Sepia con arroz y verduras","comida_cena","media",30,
   [("sepia",180,"1 unidad"),("arroz_blanco",70,"en crudo"),("pimiento",50,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea la sepia con la verdura.","Mezcla todo."]),
 R("C211","Merluza con pisto","comida_cena","media",30,
   [("merluza",180,"1 rodaja"),("tomate",100,"1 unidad"),("calabacin",70,"1/2"),("pimiento",50,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Prepara un pisto con las verduras.","Cocina la merluza encima 8 min."]),
 R("C212","Lentejas con verduras y chorizo de pavo","comida_cena","facil",30,
   [("lenteja_cocida",180,"1 plato"),("zanahoria",50,"1/2"),("cebolla",40,"1/4"),("pavo_fiambre",40,"unos dados"),("aceite_oliva",10,"1 cucharada")],
   ["Pocha la cebolla y la zanahoria.","Añade las lentejas y el pavo.","Guisa 10 min."]),
 R("C213","Solomillo de cerdo con boniato y setas","comida_cena","media",30,
   [("cerdo_solomillo",150,"1 unidad"),("boniato",150,"1 unidad"),("setas",100,"1 puñado"),("aceite_oliva",10,"1 cucharada")],
   ["Asa el boniato.","Saltea las setas.","Marca el solomillo y sirve."]),
 R("C214","Pollo con pasta y tomate","comida_cena","facil",25,
   [("pasta",80,"en crudo"),("pollo_pechuga",130,"1 filete"),("tomate",120,"1 unidad"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la pasta.","Saltea el pollo con la cebolla y el tomate.","Mezcla con la pasta."]),
 R("C215","Atun fresco con quinoa y pimientos","comida_cena","facil",25,
   [("atun_fresco",160,"1 rodaja"),("quinoa",60,"1/2 vaso"),("pimiento",80,"1 unidad"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa.","Asa los pimientos.","Marca el atun vuelta y vuelta y sirve."]),
 R("C216","Alubias con calabaza y verduras","comida_cena","facil",25,
   [("alubia_blanca",180,"1 plato"),("calabaza",120,"1 taza"),("cebolla",40,"1/4"),("tomate",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Sofrie la cebolla, la calabaza y el tomate.","Añade las alubias y guisa 10 min."]),
 R("C217","Conejo al horno con patata y pimientos","comida_cena","media",45,
   [("conejo",180,"varios trozos"),("patata",150,"1 mediana"),("pimiento",80,"1 unidad"),("aceite_oliva",12,"1 cucharada")],
   ["Coloca el conejo, la patata y el pimiento en una bandeja.","Riega con aceite y asa 35 min."]),
 R("C218","Gallo a la plancha con patata y ensalada","comida_cena","facil",25,
   [("gallo",180,"1 unidad"),("patata",120,"1 pequeña"),("lechuga",40,"unas hojas"),("tomate",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata.","Haz el gallo a la plancha.","Acompaña con la ensalada."]),
 R("C219","Pollo con lentejas y verduras","comida_cena","facil",30,
   [("pollo_pechuga",130,"1 filete"),("lenteja_cocida",150,"1 plato"),("zanahoria",50,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Pocha la verdura.","Añade las lentejas.","Sirve con el pollo a la plancha."]),
 R("C220","Rape con arroz y verduras","comida_cena","media",30,
   [("rape",180,"1 rodaja"),("arroz_blanco",70,"en crudo"),("pimiento",50,"1/2"),("guisante",50,"2 cucharadas"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz con los guisantes.","Saltea el rape con el pimiento.","Mezcla todo."]),
 R("C221","Tofu a la plancha con boniato y brocoli","comida_cena","facil",25,
   [("tofu",150,"1/2 bloque"),("boniato",150,"1 unidad"),("brocoli",120,"1/3 arbol"),("aceite_oliva",10,"1 cucharada")],
   ["Asa el boniato.","Cuece el brocoli.","Dora el tofu a la plancha y sirve."]),
 R("C222","Pavo con arroz integral y calabacin","comida_cena","facil",30,
   [("pavo_pechuga",150,"1 filete"),("arroz_integral",70,"en crudo"),("calabacin",100,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea el calabacin.","Haz el pavo a la plancha y sirve."]),
 R("C223","Ensalada de garbanzos con pimiento y atun","comida_cena","facil",15,
   [("garbanzo_cocido",180,"1 plato"),("pimiento",60,"1/2"),("tomate",70,"1/2"),("atun_lata",60,"1/2 lata"),("aceite_oliva",10,"1 cucharada")],
   ["Mezcla los garbanzos con el pimiento, el tomate y el atun.","Aliña con el aceite."]),
 R("C224","Boquerones al horno con ensalada","comida_cena","facil",20,
   [("boqueron",150,"varios"),("lechuga",50,"unas hojas"),("tomate",70,"1/2"),("cebolla",30,"1/4"),("aceite_oliva",10,"1 cucharada"),("pan_integral",40,"1 rebanada")],
   ["Hornea los boquerones 10 min.","Sirve con la ensalada y el pan."]),
 R("C225","Pollo con arroz y pisto de verduras","comida_cena","facil",30,
   [("pollo_pechuga",140,"1 filete"),("arroz_blanco",70,"en crudo"),("tomate",80,"1/2"),("calabacin",60,"1/2"),("pimiento",50,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Prepara un pisto.","Haz el pollo y sirve con el arroz y el pisto."]),
 R("C226","Merluza a la plancha con pure y zanahoria","comida_cena","facil",25,
   [("merluza",180,"1 rodaja"),("patata",130,"1 mediana"),("zanahoria",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Haz un pure con patata y zanahoria.","Haz la merluza a la plancha y sirve."]),
 R("C227","Carne picada con patata y verduras (boloñesa)","comida_cena","media",35,
   [("carne_picada",120,"1 puñado"),("patata",150,"1 mediana"),("tomate",100,"1 unidad"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Sofrie la cebolla y la carne.","Añade el tomate y cocina la salsa.","Sirve sobre la patata cocida."]),
 R("C228","Calamar con arroz y guisantes","comida_cena","media",30,
   [("calamar",180,"1 unidad"),("arroz_blanco",70,"en crudo"),("guisante",60,"2 cucharadas"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz con los guisantes.","Saltea el calamar con la cebolla.","Mezcla todo."]),
 R("C229","Pavo con boniato y pimientos","comida_cena","facil",30,
   [("pavo_pechuga",150,"1 filete"),("boniato",150,"1 unidad"),("pimiento",80,"1 unidad"),("aceite_oliva",10,"1 cucharada")],
   ["Asa el boniato y los pimientos.","Haz el pavo a la plancha y sirve."]),
 R("C230","Salmon con arroz integral y brocoli","comida_cena","facil",30,
   [("salmon",150,"1 lomo"),("arroz_integral",70,"en crudo"),("brocoli",120,"1/3 arbol"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Cuece el brocoli.","Marca el salmon y sirve."]),
 R("C231","Ensalada de pollo, aguacate y maiz","comida_cena","facil",20,
   [("pollo_pechuga",130,"1 filete"),("aguacate",60,"1/2"),("lechuga",50,"unas hojas"),("tomate",70,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Haz el pollo a la plancha y trocealo.","Monta la ensalada y aliña."]),
 R("C232","Lomo de cerdo con quinoa y verduras","comida_cena","facil",30,
   [("cerdo_lomo",150,"1 filete"),("quinoa",60,"1/2 vaso"),("pimiento",60,"1/2"),("calabacin",70,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa.","Saltea las verduras.","Haz el lomo y sirve."]),
 R("C233","Trucha al horno con patata y cebolla","comida_cena","facil",30,
   [("trucha",180,"1 unidad"),("patata",150,"1 mediana"),("cebolla",50,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Hornea la patata y la cebolla en rodajas.","Añade la trucha y hornea 12 min."]),
 R("C234","Garbanzos con arroz y verduras (cocido ligero)","comida_cena","facil",30,
   [("garbanzo_cocido",180,"1 plato"),("arroz_blanco",40,"en crudo"),("zanahoria",50,"1/2"),("patata",80,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Guisa los garbanzos con la zanahoria y la patata.","Sirve junto."]),
 R("C235","Pollo con puerro y patata al horno","comida_cena","facil",40,
   [("pollo_pechuga",150,"1 filete"),("puerro",80,"1 unidad"),("patata",150,"1 mediana"),("aceite_oliva",10,"1 cucharada")],
   ["Coloca el pollo, el puerro y la patata en una bandeja.","Riega con aceite y asa 30 min."]),
 R("C236","Bacalao con patata y pimientos al horno","comida_cena","media",35,
   [("bacalao",180,"1 lomo"),("patata",150,"1 mediana"),("pimiento",80,"1 unidad"),("aceite_oliva",10,"1 cucharada")],
   ["Asa la patata y el pimiento.","Añade el bacalao y hornea 10 min."]),
 R("C237","Sardinas con ensalada de patata","comida_cena","facil",25,
   [("sardina",150,"3-4 unidades"),("patata",150,"1 mediana"),("cebolla",30,"1/4"),("tomate",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata.","Hornea las sardinas.","Sirve con la ensalada de patata, cebolla y tomate."]),
 R("C238","Tofu revuelto con verduras y pan","comida_cena","facil",20,
   [("tofu",150,"1/2 bloque"),("pimiento",60,"1/2"),("calabacin",60,"1/2"),("cebolla",40,"1/4"),("pan_integral",40,"1 rebanada"),("aceite_oliva",10,"1 cucharada")],
   ["Saltea las verduras.","Desmenuza el tofu y saltea junto.","Sirve con el pan."]),
 R("C239","Pollo con espinacas a la crema y arroz","comida_cena","media",30,
   [("pollo_pechuga",150,"1 filete"),("espinaca",120,"2 puñados"),("leche_semi",60,"un chorro"),("arroz_blanco",60,"en crudo"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea las espinacas con la leche hasta cremar.","Sirve con el pollo a la plancha."]),
 R("C240","Merluza con guisantes y jamon","comida_cena","media",30,
   [("merluza",180,"1 rodaja"),("guisante",80,"2 cucharadas"),("jamon_serrano",25,"1 loncha"),("patata",100,"1 pequeña"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata.","Saltea los guisantes con el jamon.","Cocina la merluza y sirve junto."]),
 R("C241","Ternera a la plancha con ensalada y pan","comida_cena","facil",20,
   [("vacuno_solomillo",150,"1 filete"),("lechuga",50,"unas hojas"),("tomate",70,"1/2"),("pan_integral",40,"1 rebanada"),("aceite_oliva",10,"1 cucharada")],
   ["Haz la ternera a la plancha.","Sirve con la ensalada y el pan."]),
 R("C242","Pavo guisado con garbanzos","comida_cena","facil",30,
   [("pavo_pechuga",130,"1 filete"),("garbanzo_cocido",160,"1 plato"),("tomate",70,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Sofrie la cebolla y el tomate.","Añade el pavo en dados y los garbanzos.","Guisa 12 min."]),
 R("C243","Dorada con arroz y verduras","comida_cena","facil",30,
   [("dorada",180,"1 unidad"),("arroz_blanco",70,"en crudo"),("calabacin",70,"1/2"),("zanahoria",50,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea las verduras.","Haz la dorada y sirve."]),
 R("C244","Ensalada de pasta con pollo y verduras","comida_cena","facil",20,
   [("pasta",80,"en crudo"),("pollo_pechuga",120,"1 filete"),("tomate",70,"1/2"),("pepino",50,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la pasta y enfriala.","Añade el pollo a la plancha troceado y las verduras."]),
 R("C245","Lubina con patata panadera","comida_cena","media",35,
   [("lubina",180,"1 unidad"),("patata",150,"1 mediana"),("cebolla",50,"1/2"),("aceite_oliva",12,"1 cucharada")],
   ["Hornea la patata y la cebolla en rodajas 20 min.","Añade la lubina y hornea 12 min."]),
 R("C246","Pollo con cuscus de verduras","comida_cena","facil",25,
   [("pollo_pechuga",140,"1 filete"),("quinoa",60,"1/2 vaso"),("zanahoria",50,"1/2"),("pimiento",50,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa con las verduras.","Haz el pollo a la plancha y sirve."]),
 R("C247","Revuelto de gambas y esparragos con pan","comida_cena","facil",15,
   [("gamba",120,"1 puñado"),("esparrago",100,"1 manojo"),("huevo",120,"2 unidades"),("pan_integral",40,"1 rebanada"),("aceite_oliva",10,"1 cucharada")],
   ["Saltea los esparragos y las gambas.","Añade los huevos y cuaja.","Sirve con el pan."]),
 R("C248","Cerdo con manzana y patata","comida_cena","media",30,
   [("cerdo_lomo",150,"1 filete"),("manzana",80,"1/2"),("patata",150,"1 mediana"),("aceite_oliva",10,"1 cucharada")],
   ["Asa la patata.","Saltea el lomo con la manzana en gajos.","Sirve junto."]),
 R("C249","Ensalada tibia de lentejas y verduras","comida_cena","facil",20,
   [("lenteja_cocida",180,"1 plato"),("zanahoria",50,"1/2"),("pimiento",50,"1/2"),("cebolla",30,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Saltea la verdura.","Añade las lentejas y calienta.","Aliña con el aceite."]),
 R("C250","Pollo al limon con arroz y brocoli","comida_cena","facil",30,
   [("pollo_pechuga",150,"1 filete"),("arroz_blanco",70,"en crudo"),("brocoli",120,"1/3 arbol"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz y el brocoli.","Haz el pollo a la plancha con unas gotas de limon.","Sirve junto."]),

 # ============ MERIENDAS (25) ============
 R("M201","Yogur natural con manzana y nueces","merienda","facil",3,
   [("yogur_natural",125,"1 unidad"),("manzana",100,"1 pequeña"),("nuez",15,"2 nueces")],
   ["Pon el yogur en un bol.","Añade la manzana y las nueces."]),
 R("M202","Tostada de pan integral con pavo","merienda","facil",5,
   [("pan_integral",40,"1 rebanada"),("pavo_fiambre",40,"2 lonchas"),("tomate",50,"1/2")],
   ["Tuesta el pan.","Coloca el tomate y el pavo."]),
 R("M203","Pera y almendras","merienda","facil",2,
   [("pera",150,"1 unidad"),("almendra",20,"un puñado")],
   ["Sirve la pera con las almendras."]),
 R("M204","Yogur griego con melocoton","merienda","facil",3,
   [("yogur_griego",125,"1 unidad"),("melocoton",120,"1 unidad"),("miel",8,"1 cucharadita")],
   ["Pon el yogur en un bol.","Añade el melocoton troceado y la miel."]),
 R("M205","Batido de leche, platano y avena","merienda","facil",5,
   [("leche_semi",200,"1 vaso"),("platano",100,"1 unidad"),("avena",20,"2 cucharadas")],
   ["Tritura todos los ingredientes."]),
 R("M206","Requeson con higos y nueces","merienda","facil",3,
   [("requeson",125,"1 tarrina"),("higo",80,"1-2 unidades"),("nuez",15,"2 nueces")],
   ["Pon el requeson en un bol.","Añade los higos y las nueces."]),
 R("M207","Tostada de aguacate y tomate cherry","merienda","facil",6,
   [("pan_integral",40,"1 rebanada"),("aguacate",60,"1/2"),("tomate",50,"unos cherry")],
   ["Tuesta el pan.","Unta el aguacate y añade el tomate."]),
 R("M208","Uvas y queso fresco","merienda","facil",2,
   [("uva",120,"un racimo pequeño"),("queso_fresco",50,"unos dados")],
   ["Sirve las uvas con el queso."]),
 R("M209","Yogur natural con muesli y arandanos","merienda","facil",4,
   [("yogur_natural",125,"1 unidad"),("muesli",30,"3 cucharadas"),("arandano",60,"un puñado")],
   ["Mezcla el yogur con el muesli.","Añade los arandanos."]),
 R("M210","Chocolate negro con avellanas","merienda","facil",1,
   [("chocolate_negro",20,"2 onzas"),("avellana",15,"un puñado")],
   ["Acompaña el chocolate con las avellanas."]),
 R("M211","Platano y un puñado de anacardos","merienda","facil",2,
   [("platano",120,"1 unidad"),("anacardo",20,"un puñado")],
   ["Sirve el platano con los anacardos."]),
 R("M212","Tostada de crema de cacahuete y datiles","merienda","facil",4,
   [("pan_integral",40,"1 rebanada"),("crema_cacahuete",15,"1 cucharada"),("datil",20,"1-2 unidades")],
   ["Tuesta el pan.","Unta la crema y añade los datiles troceados."]),
 R("M213","Mandarinas con nueces","merienda","facil",2,
   [("mandarina",150,"2 unidades"),("nuez",20,"3 nueces")],
   ["Pela las mandarinas.","Acompaña con las nueces."]),
 R("M214","Yogur griego con fresas y avena","merienda","facil",4,
   [("yogur_griego",125,"1 unidad"),("fresa",100,"6-7 unidades"),("avena",20,"2 cucharadas")],
   ["Mezcla el yogur con la avena.","Añade las fresas."]),
 R("M215","Melon con jamon serrano","merienda","facil",5,
   [("melon",150,"2 tajadas"),("jamon_serrano",40,"2 lonchas")],
   ["Corta el melon.","Acompaña con el jamon."]),
 R("M216","Bastones de zanahoria con requeson","merienda","facil",4,
   [("zanahoria",120,"2 unidades"),("requeson",80,"unas cucharadas")],
   ["Corta la zanahoria en bastones.","Sirve con el requeson."]),
 R("M217","Batido de yogur, fresa y platano","merienda","facil",5,
   [("yogur_natural",125,"1 unidad"),("fresa",80,"5 unidades"),("platano",80,"1/2"),("leche_semi",80,"medio vaso")],
   ["Tritura todos los ingredientes."]),
 R("M218","Tostada con queso fresco y miel","merienda","facil",4,
   [("pan_integral",40,"1 rebanada"),("queso_fresco",50,"unas lonchas"),("miel",8,"1 cucharadita")],
   ["Tuesta el pan.","Coloca el queso y la miel."]),
 R("M219","Cerezas y pistachos","merienda","facil",2,
   [("cereza",120,"un puñado"),("pistacho",20,"un puñado")],
   ["Sirve las cerezas con los pistachos."]),
 R("M220","Manzana con crema de cacahuete y canela","merienda","facil",3,
   [("manzana",150,"1 unidad"),("crema_cacahuete",15,"1 cucharada"),("canela",1,"1 pizca")],
   ["Corta la manzana.","Unta la crema y espolvorea canela."]),
 R("M221","Yogur griego con datiles y almendras","merienda","facil",3,
   [("yogur_griego",125,"1 unidad"),("datil",20,"1-2 unidades"),("almendra",15,"un puñado")],
   ["Pon el yogur en un bol.","Añade los datiles y las almendras."]),
 R("M222","Kiwi y avellanas","merienda","facil",2,
   [("kiwi",140,"2 unidades"),("avellana",20,"un puñado")],
   ["Pela los kiwis.","Acompaña con las avellanas."]),
 R("M223","Tostada de pan de centeno con aguacate","merienda","facil",5,
   [("pan_centeno",40,"1 rebanada"),("aguacate",60,"1/2"),("tomate",50,"1/2")],
   ["Tuesta el pan.","Unta el aguacate y añade el tomate."]),
 R("M224","Naranja y un puñado de nueces","merienda","facil",2,
   [("naranja",150,"1 unidad"),("nuez",20,"3 nueces")],
   ["Pela la naranja.","Acompaña con las nueces."]),
 R("M225","Requeson con platano y canela","merienda","facil",3,
   [("requeson",125,"1 tarrina"),("platano",90,"1 unidad"),("canela",1,"1 pizca")],
   ["Pon el requeson en un bol.","Añade el platano y la canela."]),
]
