# -*- coding: utf-8 -*-
"""Lote 2 - 100 recetas nuevas (25 desayunos + 50 comidas/cenas + 25 meriendas).
Ingredientes por CLAVE canonica (ver ingredientes.py). Se resuelven a f_id BEDCA en export."""

def R(id, nombre, tipo, dif, t, ings, pasos):
    return {"id": id, "nombre": nombre, "tipo": tipo, "dificultad": dif, "tiempo_min": t,
            "raciones": 1, "_ings_clave": ings, "elaboracion": pasos}

RECETAS = [
 # ============ DESAYUNOS (25) ============
 R("D101","Tortitas de avena y platano","desayuno","facil",15,
   [("avena",50,"5 cucharadas"),("huevo",60,"1 unidad"),("platano",100,"1 unidad"),("leche_semi",50,"un chorro")],
   ["Tritura la avena con el huevo, el platano y la leche.","Cuaja pequeñas tortitas en una sarten antiadherente por ambos lados."]),
 R("D102","Tostada de aguacate y tomate","desayuno","facil",8,
   [("pan_integral",60,"2 rebanadas"),("aguacate",75,"1/2 unidad"),("tomate",80,"1/2 unidad"),("aceite_oliva",5,"1/2 cucharada")],
   ["Tuesta el pan.","Machaca el aguacate y untalo.","Añade el tomate en rodajas y un hilo de aceite."]),
 R("D103","Bowl de yogur griego con frambuesas y nueces","desayuno","facil",5,
   [("yogur_griego",125,"1 unidad"),("frambuesa",80,"un puñado"),("nuez",20,"3 nueces"),("miel",10,"1 cucharadita")],
   ["Pon el yogur en un bol.","Añade las frambuesas, las nueces y la miel."]),
 R("D104","Huevos revueltos con champiñones y pan","desayuno","facil",12,
   [("huevo",120,"2 unidades"),("champinon",80,"4 unidades"),("pan_integral",40,"1 rebanada"),("aceite_oliva",8,"1 cucharada")],
   ["Saltea los champiñones laminados.","Añade los huevos batidos y remueve hasta cuajar.","Sirve con el pan tostado."]),
 R("D105","Porridge de avena con manzana y canela","desayuno","facil",10,
   [("avena",50,"5 cucharadas"),("leche_semi",200,"1 vaso"),("manzana",100,"1 pequeña"),("canela",1,"1 pizca")],
   ["Cuece la avena con la leche 5 min.","Añade la manzana troceada y la canela."]),
 R("D106","Batido verde de espinaca y platano","desayuno","facil",5,
   [("espinaca",40,"1 puñado"),("platano",120,"1 unidad"),("leche_semi",200,"1 vaso"),("avena",20,"2 cucharadas")],
   ["Tritura todos los ingredientes hasta obtener un batido homogeneo."]),
 R("D107","Tostada de requeson con miel y nueces","desayuno","facil",5,
   [("pan_integral",60,"2 rebanadas"),("requeson",80,"unas cucharadas"),("miel",10,"1 cucharadita"),("nuez",15,"2 nueces")],
   ["Tuesta el pan.","Unta el requeson, añade la miel y las nueces."]),
 R("D108","Tortilla de claras con pavo y tomate","desayuno","facil",10,
   [("clara",120,"4 claras"),("pavo_fiambre",40,"2 lonchas"),("tomate",60,"1/2"),("aceite_oliva",5,"1/2 cucharada"),("pan_integral",40,"1 rebanada")],
   ["Bate las claras y cuajalas con el pavo troceado.","Acompaña con el tomate y el pan."]),
 R("D109","Yogur natural con muesli y fresas","desayuno","facil",5,
   [("yogur_natural",125,"1 unidad"),("muesli",40,"4 cucharadas"),("fresa",100,"6-7 unidades")],
   ["Mezcla el yogur con el muesli.","Añade las fresas troceadas."]),
 R("D110","Pan integral con queso fresco y miel","desayuno","facil",5,
   [("pan_integral",60,"2 rebanadas"),("queso_fresco",50,"unas lonchas"),("miel",10,"1 cucharadita")],
   ["Tuesta el pan.","Coloca el queso fresco y riega con la miel."]),
 R("D111","Tostada de jamon cocido y queso fresco","desayuno","facil",6,
   [("pan_integral",60,"2 rebanadas"),("jamon_cocido",40,"2 lonchas"),("queso_fresco",40,"unas lonchas"),("tomate",60,"1/2")],
   ["Tuesta el pan.","Monta con el tomate, el queso y el jamon."]),
 R("D112","Batido de leche, avena y datiles","desayuno","facil",5,
   [("leche_semi",250,"1 vaso grande"),("avena",30,"3 cucharadas"),("datil",30,"2 unidades")],
   ["Tritura la leche con la avena y los datiles deshuesados."]),
 R("D113","Bowl de kiwi, platano y yogur griego","desayuno","facil",5,
   [("yogur_griego",125,"1 unidad"),("kiwi",80,"1 unidad"),("platano",80,"1/2"),("almendra",15,"un puñado")],
   ["Pon el yogur en un bol.","Añade el kiwi y el platano en rodajas y las almendras."]),
 R("D114","Huevo cocido con tostada de aguacate","desayuno","facil",12,
   [("huevo_cocido",60,"1 unidad"),("pan_integral",60,"2 rebanadas"),("aguacate",60,"1/2"),("aceite_oliva",4,"unas gotas")],
   ["Cuece el huevo y cortalo en rodajas.","Unta el aguacate en el pan tostado y coloca el huevo."]),
 R("D115","Porridge de quinoa con leche y arandanos","desayuno","facil",20,
   [("quinoa",50,"1/2 vaso"),("leche_semi",200,"1 vaso"),("arandano",80,"un puñado"),("canela",1,"1 pizca")],
   ["Cuece la quinoa con la leche 15 min.","Añade los arandanos y la canela."]),
 R("D116","Tostada de crema de cacahuete y platano","desayuno","facil",5,
   [("pan_integral",60,"2 rebanadas"),("crema_cacahuete",20,"1 cucharada"),("platano",100,"1 unidad")],
   ["Tuesta el pan.","Unta la crema de cacahuete y añade el platano en rodajas."]),
 R("D117","Yogur griego con manzana, avena y canela","desayuno","facil",5,
   [("yogur_griego",125,"1 unidad"),("manzana",100,"1 pequeña"),("avena",25,"2 cucharadas"),("canela",1,"1 pizca")],
   ["Mezcla el yogur con la avena.","Añade la manzana troceada y la canela."]),
 R("D118","Revuelto de huevo con espinacas","desayuno","facil",10,
   [("huevo",120,"2 unidades"),("espinaca",80,"1 puñado"),("pan_integral",40,"1 rebanada"),("aceite_oliva",8,"1 cucharada")],
   ["Saltea las espinacas.","Añade los huevos y cuaja.","Sirve con el pan."]),
 R("D119","Macedonia de fruta con yogur","desayuno","facil",8,
   [("naranja",120,"1 unidad"),("kiwi",70,"1 unidad"),("manzana",100,"1 pequeña"),("yogur_natural",125,"1 unidad")],
   ["Trocea la fruta.","Sirve con el yogur por encima."]),
 R("D120","Tostada de tomate, aceite y pavo","desayuno","facil",6,
   [("pan_integral",60,"2 rebanadas"),("tomate",70,"1/2"),("aceite_oliva",8,"1 cucharada"),("pavo_fiambre",40,"2 lonchas")],
   ["Tuesta el pan y unta el tomate rallado con el aceite.","Coloca el pavo."]),
 R("D121","Batido de fresa, platano y leche","desayuno","facil",5,
   [("fresa",100,"6-7 unidades"),("platano",100,"1 unidad"),("leche_semi",200,"1 vaso"),("avena",20,"2 cucharadas")],
   ["Tritura todos los ingredientes hasta que quede cremoso."]),
 R("D122","Tortitas de avena con miel y fresas","desayuno","facil",15,
   [("avena",50,"5 cucharadas"),("huevo",60,"1 unidad"),("miel",10,"1 cucharadita"),("fresa",80,"5 unidades")],
   ["Tritura la avena con el huevo y haz tortitas.","Sirve con la miel y las fresas."]),
 R("D123","Pan de centeno con aguacate y huevo","desayuno","facil",12,
   [("pan_centeno",60,"2 rebanadas"),("aguacate",70,"1/2"),("huevo_cocido",60,"1 unidad")],
   ["Tuesta el pan.","Unta el aguacate y coloca el huevo en rodajas."]),
 R("D124","Bowl de requeson con pera y nueces","desayuno","facil",5,
   [("requeson",125,"1 tarrina"),("pera",120,"1 unidad"),("nuez",20,"3 nueces"),("miel",10,"1 cucharadita")],
   ["Pon el requeson en un bol.","Añade la pera troceada, las nueces y la miel."]),
 R("D125","Yogur con platano, avena y cacahuetes","desayuno","facil",5,
   [("yogur_natural",125,"1 unidad"),("platano",100,"1 unidad"),("avena",25,"2 cucharadas"),("cacahuete",15,"un puñado")],
   ["Mezcla el yogur con la avena.","Añade el platano y los cacahuetes."]),

 # ============ COMIDAS / CENAS (50) ============
 R("C101","Pollo al horno con boniato y brocoli","comida_cena","facil",35,
   [("pollo_pechuga",150,"1 filete"),("boniato",150,"1 unidad"),("brocoli",150,"1/2 arbol"),("aceite_oliva",10,"1 cucharada")],
   ["Asa el boniato en gajos 25 min.","Hornea el pollo 15 min.","Cuece el brocoli al vapor y sirve todo junto."]),
 R("C102","Salmon con quinoa y espinacas","comida_cena","facil",25,
   [("salmon",150,"1 lomo"),("quinoa",60,"1/2 vaso"),("espinaca",120,"2 puñados"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa.","Saltea las espinacas.","Marca el salmon a la plancha y sirve."]),
 R("C103","Dorada a la plancha con patata y ensalada","comida_cena","facil",30,
   [("dorada",180,"1 unidad"),("patata",150,"1 mediana"),("lechuga",40,"unas hojas"),("tomate",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata.","Haz la dorada a la plancha.","Acompaña con la ensalada aliñada."]),
 R("C104","Lentejas con arroz y verduras","comida_cena","facil",30,
   [("lenteja_cocida",180,"1 plato"),("arroz_blanco",40,"en crudo"),("zanahoria",50,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Pocha la cebolla y la zanahoria.","Añade las lentejas y el arroz y calienta."]),
 R("C105","Pavo con pure de calabaza y champiñones","comida_cena","facil",30,
   [("pavo_pechuga",150,"1 filete"),("calabaza",200,"1 taza"),("champinon",100,"5-6 unidades"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la calabaza y haz un pure.","Saltea los champiñones.","Haz el pavo a la plancha y sirve."]),
 R("C106","Merluza al horno con patata y guisantes","comida_cena","facil",30,
   [("merluza",180,"1 rodaja"),("patata",150,"1 mediana"),("guisante",80,"2 cucharadas"),("aceite_oliva",10,"1 cucharada")],
   ["Hornea la patata en rodajas 15 min.","Añade la merluza y hornea 12 min.","Cuece los guisantes y sirve."]),
 R("C107","Ternera con arroz integral y pimientos","comida_cena","media",30,
   [("vacuno_solomillo",150,"1 filete"),("arroz_integral",70,"en crudo"),("pimiento",80,"1 unidad"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea el pimiento y la cebolla.","Añade la ternera en tiras y sirve con el arroz."]),
 R("C108","Garbanzos con espinacas y huevo","comida_cena","facil",25,
   [("garbanzo_cocido",180,"1 plato"),("espinaca",150,"2 puñados"),("huevo_cocido",60,"1 unidad"),("tomate",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Sofrie el tomate y las espinacas.","Añade los garbanzos y calienta.","Sirve con el huevo cocido."]),
 R("C109","Lubina con verduras al horno","comida_cena","media",35,
   [("lubina",180,"1 unidad"),("calabacin",100,"1/2"),("pimiento",70,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Coloca las verduras en juliana en una bandeja y hornea 15 min.","Añade la lubina y hornea 12 min mas."]),
 R("C110","Pollo salteado con verduras y arroz","comida_cena","facil",30,
   [("pollo_pechuga",140,"1 filete"),("arroz_blanco",70,"en crudo"),("calabacin",70,"1/2"),("zanahoria",50,"1/2"),("pimiento",50,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea el pollo en dados.","Añade las verduras en juliana y mezcla con el arroz."]),
 R("C111","Bacalao con pisto","comida_cena","media",35,
   [("bacalao",180,"1 lomo"),("tomate",100,"1 unidad"),("calabacin",80,"1/2"),("pimiento",60,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",12,"1 cucharada")],
   ["Sofrie cebolla, pimiento y calabacin.","Añade el tomate y cocina el pisto.","Cocina el bacalao encima 8 min."]),
 R("C112","Conejo al ajillo con patata","comida_cena","media",40,
   [("conejo",180,"varios trozos"),("patata",150,"1 mediana"),("ajo",8,"2 dientes"),("aceite_oliva",12,"1 cucharada")],
   ["Dora el conejo con el ajo.","Añade un poco de agua y guisa 25 min.","Sirve con la patata cocida."]),
 R("C113","Ensalada de quinoa, tomate, pepino y atun","comida_cena","facil",20,
   [("quinoa",60,"1/2 vaso"),("tomate",80,"1/2"),("pepino",60,"1/4"),("atun_lata",60,"1/2 lata"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa y enfriala.","Mezcla con el tomate, el pepino y el atun.","Aliña con el aceite."]),
 R("C114","Pasta con tomate y carne picada","comida_cena","facil",25,
   [("pasta",80,"en crudo"),("tomate",120,"1 unidad"),("carne_picada",100,"1 puñado"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la pasta.","Sofrie la cebolla y la carne.","Añade el tomate, cocina la salsa y mezcla con la pasta."]),
 R("C115","Trucha a la plancha con arroz y judias","comida_cena","facil",25,
   [("trucha",180,"1 unidad"),("arroz_blanco",70,"en crudo"),("judia_verde",120,"2 puñados"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz y las judias.","Haz la trucha a la plancha y sirve."]),
 R("C116","Alubias blancas con verduras","comida_cena","facil",25,
   [("alubia_blanca",180,"1 plato"),("zanahoria",50,"1/2"),("cebolla",40,"1/4"),("tomate",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Pocha la cebolla y la zanahoria.","Añade el tomate y las alubias.","Guisa 10 min."]),
 R("C117","Solomillo de cerdo con patata y pimientos","comida_cena","facil",30,
   [("cerdo_solomillo",150,"1 unidad"),("patata",150,"1 mediana"),("pimiento",100,"1 unidad"),("aceite_oliva",10,"1 cucharada")],
   ["Asa la patata y los pimientos.","Marca el solomillo en medallones y sirve."]),
 R("C118","Calamares a la plancha con ensalada","comida_cena","facil",20,
   [("calamar",200,"1 unidad"),("lechuga",50,"unas hojas"),("tomate",70,"1/2"),("cebolla",30,"1/4"),("aceite_oliva",10,"1 cucharada"),("pan_integral",40,"1 rebanada")],
   ["Haz los calamares a la plancha con ajo.","Sirve con la ensalada y el pan."]),
 R("C119","Pollo con quinoa y verduras","comida_cena","facil",30,
   [("pollo_pechuga",140,"1 filete"),("quinoa",60,"1/2 vaso"),("calabacin",80,"1/2"),("pimiento",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa.","Saltea el pollo y las verduras.","Mezcla todo."]),
 R("C120","Rape con patata y guisantes","comida_cena","media",30,
   [("rape",180,"1 rodaja"),("patata",150,"1 mediana"),("guisante",80,"2 cucharadas"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata y los guisantes.","Haz el rape a la plancha o al horno 12 min."]),
 R("C121","Tofu salteado con brocoli y arroz","comida_cena","facil",25,
   [("tofu",150,"1/2 bloque"),("arroz_integral",70,"en crudo"),("brocoli",120,"1/3 arbol"),("zanahoria",50,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Dora el tofu en dados.","Saltea el brocoli y la zanahoria e incorpora el tofu."]),
 R("C122","Pavo con boniato y judias verdes","comida_cena","facil",30,
   [("pavo_pechuga",150,"1 filete"),("boniato",150,"1 unidad"),("judia_verde",120,"2 puñados"),("aceite_oliva",10,"1 cucharada")],
   ["Asa el boniato.","Cuece las judias.","Haz el pavo a la plancha y sirve."]),
 R("C123","Ensalada de lentejas con verduras","comida_cena","facil",15,
   [("lenteja_cocida",180,"1 plato"),("tomate",80,"1/2"),("pepino",60,"1/4"),("cebolla",30,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Mezcla las lentejas frias con el tomate, el pepino y la cebolla.","Aliña con el aceite."]),
 R("C124","Sardinas al horno con pimientos y patata","comida_cena","facil",25,
   [("sardina",150,"3-4 unidades"),("pimiento",80,"1/2"),("patata",120,"1 pequeña"),("aceite_oliva",10,"1 cucharada")],
   ["Asa la patata y el pimiento.","Hornea las sardinas 10 min y sirve."]),
 R("C125","Pollo con arroz integral y calabacin","comida_cena","facil",30,
   [("pollo_pechuga",150,"1 filete"),("arroz_integral",70,"en crudo"),("calabacin",100,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea el calabacin.","Haz el pollo a la plancha y sirve."]),
 R("C126","Merluza con verduras al vapor","comida_cena","facil",25,
   [("merluza",180,"1 rodaja"),("patata",120,"1 pequeña"),("zanahoria",60,"1/2"),("judia_verde",100,"1 puñado"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece al vapor la patata, la zanahoria y las judias.","Cocina la merluza al vapor 8 min y aliña con el aceite."]),
 R("C127","Ternera guisada con patata y zanahoria","comida_cena","media",50,
   [("vacuno_solomillo",150,"1 filete"),("patata",150,"1 mediana"),("zanahoria",60,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Dora la ternera en dados.","Añade la verdura y agua y guisa 35 min."]),
 R("C128","Garbanzos con bacalao y espinacas","comida_cena","media",30,
   [("garbanzo_cocido",180,"1 plato"),("bacalao",120,"1 trozo"),("espinaca",120,"2 puñados"),("tomate",60,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Sofrie el tomate y las espinacas.","Añade los garbanzos y el bacalao desmigado.","Guisa 8 min."]),
 R("C129","Pulpo con patata","comida_cena","media",40,
   [("pulpo",200,"1 pata"),("patata",150,"1 mediana"),("aceite_oliva",12,"1 cucharada")],
   ["Cuece el pulpo hasta que este tierno.","Sirve sobre patata cocida con aceite y pimenton."]),
 R("C130","Pavo con quinoa y verduras","comida_cena","facil",30,
   [("pavo_pechuga",150,"1 filete"),("quinoa",60,"1/2 vaso"),("pimiento",60,"1/2"),("calabacin",70,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa.","Saltea las verduras.","Haz el pavo a la plancha y mezcla."]),
 R("C131","Atun fresco a la plancha con ensalada","comida_cena","facil",20,
   [("atun_fresco",160,"1 rodaja"),("lechuga",50,"unas hojas"),("tomate",70,"1/2"),("cebolla",30,"1/4"),("aceite_oliva",10,"1 cucharada"),("pan_integral",40,"1 rebanada")],
   ["Marca el atun a la plancha vuelta y vuelta.","Sirve con la ensalada y el pan."]),
 R("C132","Berenjenas rellenas de pollo","comida_cena","media",45,
   [("berenjena",200,"1 unidad"),("pollo_pechuga",120,"1 filete"),("tomate",80,"1/2"),("cebolla",40,"1/4"),("queso_curado",20,"para gratinar"),("aceite_oliva",10,"1 cucharada")],
   ["Asa la berenjena y retira la pulpa.","Sofrie cebolla, pulpa, pollo y tomate.","Rellena, cubre con queso y gratina."]),
 R("C133","Lomo de cerdo con pure y setas","comida_cena","facil",30,
   [("cerdo_lomo",150,"1 filete"),("patata",150,"1 mediana"),("setas",100,"1 puñado"),("aceite_oliva",10,"1 cucharada")],
   ["Haz un pure con la patata.","Saltea las setas.","Marca el lomo y sirve."]),
 R("C134","Gambas con arroz y verduras","comida_cena","facil",25,
   [("gamba",150,"1 plato"),("arroz_blanco",70,"en crudo"),("pimiento",60,"1/2"),("guisante",60,"2 cucharadas"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz con los guisantes.","Saltea las gambas y el pimiento.","Mezcla todo."]),
 R("C135","Ensalada campera con atun y huevo","comida_cena","facil",20,
   [("patata",150,"1 mediana"),("atun_lata",60,"1/2 lata"),("huevo_cocido",60,"1 unidad"),("tomate",80,"1/2"),("cebolla",30,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata y el huevo.","Mezcla con el tomate, la cebolla y el atun.","Aliña con el aceite."]),
 R("C136","Coliflor salteada con jamon y huevo","comida_cena","facil",25,
   [("coliflor",200,"1 plato"),("jamon_serrano",40,"2 lonchas"),("huevo",60,"1 unidad"),("ajo",5,"1 diente"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la coliflor.","Saltea con el ajo y el jamon.","Añade el huevo y cuaja."]),
 R("C137","Salmon al horno con boniato y esparragos","comida_cena","facil",30,
   [("salmon",150,"1 lomo"),("boniato",150,"1 unidad"),("esparrago",100,"1 manojo"),("aceite_oliva",10,"1 cucharada")],
   ["Asa el boniato.","Añade el salmon y los esparragos y hornea 12 min."]),
 R("C138","Pollo con ensalada de garbanzos","comida_cena","facil",20,
   [("pollo_pechuga",140,"1 filete"),("garbanzo_cocido",150,"1 plato"),("tomate",70,"1/2"),("pepino",60,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Haz el pollo a la plancha y trocealo.","Mezcla con los garbanzos, el tomate y el pepino."]),
 R("C139","Caballa a la plancha con pisto","comida_cena","media",30,
   [("caballa",170,"1 unidad"),("tomate",100,"1 unidad"),("calabacin",80,"1/2"),("pimiento",60,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Prepara un pisto con las verduras.","Haz la caballa a la plancha y sirve sobre el pisto."]),
 R("C140","Espinacas con garbanzos y huevo","comida_cena","facil",20,
   [("espinaca",150,"2 puñados"),("garbanzo_cocido",180,"1 plato"),("huevo_cocido",60,"1 unidad"),("ajo",5,"1 diente"),("aceite_oliva",10,"1 cucharada")],
   ["Rehoga las espinacas con el ajo.","Añade los garbanzos y calienta.","Sirve con el huevo."]),
 R("C141","Pavo con arroz y champiñones","comida_cena","facil",30,
   [("pavo_pechuga",150,"1 filete"),("arroz_blanco",70,"en crudo"),("champinon",100,"5-6 unidades"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea la cebolla y los champiñones.","Añade el pavo en dados y mezcla."]),
 R("C142","Lenguado con patata y judias","comida_cena","facil",25,
   [("lenguado",180,"1 unidad"),("patata",150,"1 mediana"),("judia_verde",120,"2 puñados"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la patata y las judias.","Haz el lenguado a la plancha y sirve."]),
 R("C143","Tofu con quinoa y verduras","comida_cena","facil",25,
   [("tofu",150,"1/2 bloque"),("quinoa",60,"1/2 vaso"),("calabacin",70,"1/2"),("pimiento",60,"1/2"),("zanahoria",50,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la quinoa.","Dora el tofu y saltea las verduras.","Mezcla todo."]),
 R("C144","Ensalada de pasta con atun y aceitunas","comida_cena","facil",20,
   [("pasta",80,"en crudo"),("atun_lata",60,"1/2 lata"),("tomate",80,"1/2"),("aceituna",20,"unas aceitunas"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece la pasta y enfriala.","Mezcla con el atun, el tomate y las aceitunas."]),
 R("C145","Pollo guisado con guisantes y zanahoria","comida_cena","media",40,
   [("pollo_pechuga",150,"1 filete"),("guisante",70,"2 cucharadas"),("zanahoria",60,"1/2"),("patata",120,"1 pequeña"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Dora el pollo en dados.","Añade la verdura y agua y guisa 25 min."]),
 R("C146","Merluza con arroz y guisantes","comida_cena","facil",25,
   [("merluza",180,"1 rodaja"),("arroz_blanco",70,"en crudo"),("guisante",70,"2 cucharadas"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz con los guisantes.","Haz la merluza a la plancha y sirve."]),
 R("C147","Lomo de cerdo con pimientos y arroz","comida_cena","facil",30,
   [("cerdo_lomo",150,"1 filete"),("arroz_blanco",70,"en crudo"),("pimiento",80,"1 unidad"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Cuece el arroz.","Saltea el pimiento y la cebolla.","Haz el lomo a la plancha y sirve."]),
 R("C148","Mejillones con arroz","comida_cena","facil",25,
   [("mejillon",180,"1 plato"),("arroz_blanco",70,"en crudo"),("tomate",80,"1/2"),("cebolla",40,"1/4"),("aceite_oliva",10,"1 cucharada")],
   ["Abre los mejillones al vapor.","Sofrie el tomate y la cebolla, añade el arroz y el caldo y cuece.","Incorpora los mejillones."]),
 R("C149","Ensalada de alubias, atun y cebolla","comida_cena","facil",15,
   [("alubia_blanca",180,"1 plato"),("atun_lata",60,"1/2 lata"),("cebolla",30,"1/4"),("tomate",70,"1/2"),("aceite_oliva",10,"1 cucharada")],
   ["Mezcla las alubias con el atun, la cebolla y el tomate.","Aliña con el aceite."]),
 R("C150","Bonito con pisto y patata","comida_cena","media",35,
   [("bonito",150,"1 rodaja"),("tomate",100,"1 unidad"),("pimiento",60,"1/2"),("calabacin",70,"1/2"),("patata",120,"1 pequeña"),("aceite_oliva",12,"1 cucharada")],
   ["Prepara un pisto con las verduras.","Cuece la patata.","Marca el bonito y sirve con el pisto."]),

 # ============ MERIENDAS (25) ============
 R("M101","Yogur griego con arandanos y almendras","merienda","facil",3,
   [("yogur_griego",125,"1 unidad"),("arandano",80,"un puñado"),("almendra",15,"un puñado")],
   ["Pon el yogur en un bol.","Añade los arandanos y las almendras."]),
 R("M102","Tostada de aguacate y tomate","merienda","facil",6,
   [("pan_integral",40,"1 rebanada"),("aguacate",60,"1/2"),("tomate",50,"1/2")],
   ["Tuesta el pan.","Unta el aguacate y añade el tomate."]),
 R("M103","Manzana con crema de cacahuete","merienda","facil",3,
   [("manzana",150,"1 unidad"),("crema_cacahuete",20,"1 cucharada")],
   ["Corta la manzana en gajos.","Acompaña con la crema de cacahuete."]),
 R("M104","Pera y un puñado de nueces","merienda","facil",2,
   [("pera",150,"1 unidad"),("nuez",20,"3 nueces")],
   ["Sirve la pera con las nueces."]),
 R("M105","Yogur natural con muesli y platano","merienda","facil",4,
   [("yogur_natural",125,"1 unidad"),("muesli",30,"3 cucharadas"),("platano",80,"1/2")],
   ["Mezcla el yogur con el muesli.","Añade el platano en rodajas."]),
 R("M106","Requeson con miel y nueces","merienda","facil",3,
   [("requeson",125,"1 tarrina"),("miel",10,"1 cucharadita"),("nuez",15,"2 nueces")],
   ["Pon el requeson en un bol.","Añade la miel y las nueces."]),
 R("M107","Batido de leche, fresa y avena","merienda","facil",5,
   [("leche_semi",200,"1 vaso"),("fresa",100,"6-7 unidades"),("avena",20,"2 cucharadas")],
   ["Tritura todos los ingredientes."]),
 R("M108","Tostada con pavo y queso fresco","merienda","facil",5,
   [("pan_integral",40,"1 rebanada"),("pavo_fiambre",40,"2 lonchas"),("queso_fresco",40,"unas lonchas")],
   ["Tuesta el pan.","Coloca el queso y el pavo."]),
 R("M109","Mandarinas y almendras","merienda","facil",2,
   [("mandarina",150,"2 unidades"),("almendra",20,"un puñado")],
   ["Pela las mandarinas.","Acompaña con las almendras."]),
 R("M110","Yogur griego con kiwi y pistachos","merienda","facil",4,
   [("yogur_griego",125,"1 unidad"),("kiwi",80,"1 unidad"),("pistacho",15,"un puñado")],
   ["Pon el yogur en un bol.","Añade el kiwi y los pistachos."]),
 R("M111","Bastones de zanahoria y pepino con requeson","merienda","facil",5,
   [("zanahoria",100,"1 unidad"),("pepino",100,"1/2"),("requeson",80,"unas cucharadas")],
   ["Corta la verdura en bastones.","Sirve con el requeson como dip."]),
 R("M112","Chocolate negro con almendras","merienda","facil",1,
   [("chocolate_negro",20,"2 onzas"),("almendra",15,"un puñado")],
   ["Acompaña el chocolate con las almendras."]),
 R("M113","Platano con crema de cacahuete","merienda","facil",3,
   [("platano",120,"1 unidad"),("crema_cacahuete",15,"1 cucharada")],
   ["Corta el platano y unta la crema de cacahuete."]),
 R("M114","Uvas y queso curado","merienda","facil",2,
   [("uva",120,"un racimo pequeño"),("queso_curado",30,"unos dados")],
   ["Sirve las uvas con los dados de queso."]),
 R("M115","Tostada de requeson y arandanos","merienda","facil",4,
   [("pan_integral",40,"1 rebanada"),("requeson",60,"unas cucharadas"),("arandano",60,"un puñado")],
   ["Tuesta el pan.","Unta el requeson y añade los arandanos."]),
 R("M116","Batido de platano, leche y cacao","merienda","facil",5,
   [("leche_semi",200,"1 vaso"),("platano",100,"1 unidad"),("chocolate_negro",10,"1 onza")],
   ["Tritura la leche con el platano.","Añade el chocolate rallado."]),
 R("M117","Yogur natural con datiles y nueces","merienda","facil",3,
   [("yogur_natural",125,"1 unidad"),("datil",25,"2 unidades"),("nuez",15,"2 nueces")],
   ["Pon el yogur en un bol.","Añade los datiles troceados y las nueces."]),
 R("M118","Melon con jamon serrano","merienda","facil",5,
   [("melon",150,"2 tajadas"),("jamon_serrano",40,"2 lonchas")],
   ["Corta el melon.","Acompaña con el jamon."]),
 R("M119","Higos con queso fresco y miel","merienda","facil",4,
   [("higo",100,"2 unidades"),("queso_fresco",60,"unas lonchas"),("miel",8,"1 cucharadita")],
   ["Corta los higos.","Sirve con el queso y la miel."]),
 R("M120","Cerezas y avellanas","merienda","facil",2,
   [("cereza",120,"un puñado"),("avellana",20,"un puñado")],
   ["Sirve las cerezas con las avellanas."]),
 R("M121","Tostada de aguacate y huevo","merienda","facil",10,
   [("pan_integral",40,"1 rebanada"),("aguacate",50,"1/3"),("huevo_cocido",60,"1 unidad")],
   ["Tuesta el pan.","Unta el aguacate y coloca el huevo en rodajas."]),
 R("M122","Manzana con canela y nueces","merienda","facil",8,
   [("manzana",150,"1 unidad"),("canela",1,"1 pizca"),("nuez",15,"2 nueces"),("miel",8,"1 cucharadita")],
   ["Trocea la manzana, espolvorea canela y calienta en el microondas 2 min.","Añade las nueces y la miel."]),
 R("M123","Yogur griego con avena, miel y pasas","merienda","facil",4,
   [("yogur_griego",125,"1 unidad"),("avena",25,"2 cucharadas"),("miel",8,"1 cucharadita"),("pasas",15,"un puñado")],
   ["Mezcla el yogur con la avena.","Añade la miel y las pasas."]),
 R("M124","Naranja y anacardos","merienda","facil",2,
   [("naranja",150,"1 unidad"),("anacardo",20,"un puñado")],
   ["Pela la naranja.","Acompaña con los anacardos."]),
 R("M125","Pan con tomate, aceite y jamon serrano","merienda","facil",6,
   [("pan_integral",40,"1 rebanada"),("tomate",50,"1/2"),("aceite_oliva",8,"1 cucharada"),("jamon_serrano",30,"1 loncha")],
   ["Tuesta el pan y unta el tomate con el aceite.","Coloca el jamon."]),
]
