# -*- coding: utf-8 -*-
"""100 recetas elaboradas (tipo comida_cena): pastas, arroces, pollo, verduras,
pescados, sandwiches y bocadillos. Ingredientes por f_id de BEDCA.
Pesos de carne/pescado/pasta/arroz en CRUDO salvo indicacion."""

def _r(id, nombre, dif, t, ings, pasos):
    return {"id": id, "nombre": nombre, "tipo": "comida_cena", "dificultad": dif,
            "tiempo_min": t, "raciones": 1,
            "ingredientes": [{"f_id": f, "nombre": nm, "gramos": g, "casera": c} for f, nm, g, c in ings],
            "elaboracion": pasos}

# --- atajos de ingredientes frecuentes ---
AOVE   = ("2544", "Aceite de oliva virgen extra", 10, "1 cucharada")
AOVE_S = ("2544", "Aceite de oliva virgen extra", 5, "1/2 cucharada")
AJO    = ("1774", "Ajo", 5, "1 diente")
AJO2   = ("1774", "Ajo", 8, "2 dientes")
CEBOLLA= ("1773", "Cebolla", 60, "1/2 unidad")
CEB_S  = ("1773", "Cebolla", 35, "1/4 unidad")
TOMATE = ("1879", "Tomate", 100, "1 unidad")
T_FRITO= ("1759", "Tomate frito", 60, "3 cucharadas")
PEREJIL= ("1374", "Perejil fresco", 3, "picado")
LECHUGA= ("1775", "Lechuga", 30, "unas hojas")
PAN_BAR= ("1810", "Pan de barra", 80, "1 bocadillo")
PAN_MOL= ("1792", "Pan de molde", 60, "2 rebanadas")
PAN_INT= ("2164", "Pan integral de molde", 60, "2 rebanadas")
PASTA  = ("1117", "Pasta", 80, "1 plato en crudo")
ARROZ  = ("1630", "Arroz", 80, "1 vaso en crudo")

RECETAS = [

 # ═══════════ PASTAS (15) ═══════════
 _r("E001", "Espaguetis a la carbonara", "media", 25,
    [PASTA, ("2260", "Panceta", 60, "unos tacos"), ("2127", "Huevo", 60, "1 unidad"),
     ("1872", "Queso parmesano", 25, "rallado"), AJO, AOVE_S],
    ["Pon a cocer la pasta en abundante agua con sal.",
     "Corta la panceta en tacos y dorala en la sarten con el ajo y un poco de aceite. Retira el ajo.",
     "Bate el huevo con el parmesano rallado y pimienta negra abundante.",
     "Escurre la pasta reservando un vaso del agua de coccion.",
     "Fuera del fuego, mezcla la pasta con la panceta y añade el huevo batido removiendo rapido.",
     "Añade agua de coccion poco a poco hasta que quede cremoso, sin que el huevo cuaje."]),
 _r("E002", "Macarrones a la bolognesa", "media", 40,
    [PASTA, ("1931", "Carne picada de ternera", 120, "1 puñado"), CEBOLLA, ("1892", "Zanahoria", 50, "1/2"),
     ("1759", "Tomate frito", 120, "1 vaso"), AJO, AOVE],
    ["Pica muy fina la cebolla, la zanahoria y el ajo, y pochalos en el aceite 8 min.",
     "Sube el fuego, añade la carne picada y dorala desmenuzandola.",
     "Incorpora el tomate, salpimenta y cocina a fuego lento 20 min.",
     "Cuece la pasta al dente y mezclala con la salsa."]),
 _r("E003", "Pasta al pesto con pollo y tomate cherry", "facil", 25,
    [PASTA, ("994", "Pechuga de pollo", 120, "1 filete"), ("2201", "Nueces", 15, "2 nueces"),
     ("1872", "Queso parmesano", 20, "rallado"), ("1879", "Tomate cherry", 80, "un puñado"), AJO, AOVE],
    ["Tritura las nueces con el ajo, el parmesano, el aceite y albahaca hasta formar el pesto.",
     "Cuece la pasta al dente.",
     "Haz el pollo a la plancha en tiras y saltea los tomates cherry partidos.",
     "Mezcla todo con el pesto y un poco de agua de coccion."]),
 _r("E004", "Lasaña de carne y verduras", "alta", 60,
    [("1117", "Placas de lasaña", 70, "4 placas"), ("1931", "Carne picada de ternera", 110, "1 puñado"),
     CEBOLLA, ("2378", "Calabacin", 70, "1/2"), ("1759", "Tomate frito", 100, "1 vaso"),
     ("1694", "Leche entera", 100, "1/2 vaso"), ("1901", "Queso curado", 30, "rallado"), AOVE],
    ["Pocha la cebolla y el calabacin picados, añade la carne y dorala.",
     "Incorpora el tomate y cocina 15 min a fuego lento.",
     "Prepara una bechamel ligera con la leche y una cucharadita de harina.",
     "Hidrata las placas segun el paquete.",
     "Monta capas: placa, carne, placa, carne... y cubre con bechamel y queso.",
     "Gratina al horno 15 min a 200 grados hasta dorar."]),
 _r("E005", "Pasta con gambas al ajillo y calabacin", "media", 25,
    [PASTA, ("817", "Gambas", 120, "1 plato"), ("1776", "Calabacin", 80, "1/2"), AJO2,
     ("2462", "Vino blanco", 30, "un chorro"), PEREJIL, AOVE],
    ["Cuece la pasta al dente.",
     "Dora los ajos laminados en el aceite sin que se quemen.",
     "Añade las gambas peladas y saltealas 2 min.",
     "Incorpora el calabacin en dados, riega con el vino y deja evaporar.",
     "Mezcla con la pasta y espolvorea perejil."]),
 _r("E006", "Macarrones gratinados con atun", "facil", 30,
    [PASTA, ("2131", "Atun en aceite (escurrido)", 80, "1 lata"), ("1759", "Tomate frito", 100, "1 vaso"),
     CEB_S, ("2510", "Queso mozzarella", 40, "para gratinar"), AOVE_S],
    ["Cuece la pasta al dente.",
     "Sofrie la cebolla picada, añade el tomate y el atun escurrido.",
     "Mezcla con la pasta en una fuente de horno.",
     "Cubre con la mozzarella y gratina 10 min."]),
 _r("E007", "Espaguetis con almejas y perejil", "media", 25,
    [PASTA, ("1710", "Almejas", 150, "1 plato"), AJO2, ("2462", "Vino blanco", 40, "un chorro"),
     PEREJIL, AOVE],
    ["Limpia las almejas en agua con sal.",
     "Dora los ajos laminados, añade las almejas y el vino y tapa hasta que abran.",
     "Cuece la pasta al dente y añadela a la sarten con un poco de agua de coccion.",
     "Remueve para ligar la salsa y termina con perejil."]),
 _r("E008", "Pasta integral con pollo al curry", "media", 30,
    [("1074", "Pasta integral", 80, "1 plato en crudo"), ("994", "Pechuga de pollo", 130, "1 filete"),
     CEBOLLA, ("1992", "Curry", 3, "1 cucharadita"), ("1694", "Leche entera", 80, "un chorro"), AOVE],
    ["Cuece la pasta integral al dente.",
     "Pocha la cebolla y añade el pollo en dados hasta dorar.",
     "Espolvorea el curry, remueve 1 min y añade la leche.",
     "Deja reducir hasta que espese y mezcla con la pasta."]),
 _r("E009", "Canelones de carne", "alta", 55,
    [("1117", "Placas de canelones", 70, "4 unidades"), ("1931", "Carne picada de ternera", 110, "1 puñado"),
     CEB_S, ("1759", "Tomate frito", 60, "3 cucharadas"), ("1694", "Leche entera", 120, "1/2 vaso"),
     ("1901", "Queso curado", 25, "rallado"), AOVE],
    ["Pocha la cebolla, añade la carne y dorala bien. Incorpora el tomate y deja reducir.",
     "Hidrata las placas y rellenalas con la carne, enrollandolas.",
     "Prepara una bechamel ligera con la leche.",
     "Coloca los canelones en la fuente, cubre con bechamel y queso.",
     "Gratina 15 min a 200 grados."]),
 _r("E010", "Pasta a la putanesca", "media", 25,
    [PASTA, ("1879", "Tomate", 150, "1 y 1/2"), ("1619", "Aceitunas negras", 30, "un puñado"),
     ("2131", "Atun en aceite (escurrido)", 60, "1/2 lata"), AJO2, ("1353", "Oregano", 1, "1 pizca"), AOVE],
    ["Dora los ajos laminados en el aceite.",
     "Añade el tomate troceado y cocina 10 min.",
     "Incorpora las aceitunas, el atun y el oregano.",
     "Mezcla con la pasta cocida al dente."]),
 _r("E011", "Espaguetis con boloñesa de lentejas", "media", 35,
    [PASTA, ("1126", "Lentejas cocidas", 150, "1 plato"), CEBOLLA, ("1892", "Zanahoria", 50, "1/2"),
     ("1759", "Tomate frito", 100, "1 vaso"), AJO, AOVE],
    ["Pocha la cebolla, la zanahoria y el ajo bien picados.",
     "Añade las lentejas escurridas y machacalas ligeramente con el tenedor.",
     "Incorpora el tomate y cocina 15 min a fuego lento.",
     "Sirve sobre la pasta cocida al dente."]),
 _r("E012", "Pasta con salmon y espinacas", "facil", 25,
    [PASTA, ("2626", "Salmon", 120, "1 lomo"), ("2395", "Espinacas", 100, "2 puñados"),
     ("1694", "Leche entera", 80, "un chorro"), AJO, AOVE],
    ["Cuece la pasta al dente.",
     "Saltea el ajo y las espinacas hasta que reduzcan.",
     "Añade el salmon en dados y cocinalo 3 min.",
     "Incorpora la leche, deja espesar y mezcla con la pasta."]),
 _r("E013", "Macarrones con chorizo y pimiento", "facil", 30,
    [PASTA, ("1661", "Chorizo", 50, "unas rodajas"), ("1894", "Pimiento rojo", 70, "1/2"),
     CEB_S, ("1759", "Tomate frito", 90, "1/2 vaso"), AOVE_S],
    ["Sofrie la cebolla y el pimiento en tiras.",
     "Añade el chorizo en rodajas y dora 2 min.",
     "Incorpora el tomate y cocina 10 min.",
     "Mezcla con la pasta cocida."]),
 _r("E014", "Pasta primavera con verduras salteadas", "facil", 25,
    [PASTA, ("1776", "Calabacin", 70, "1/2"), ("1894", "Pimiento rojo", 60, "1/2"),
     ("1892", "Zanahoria", 50, "1/2"), ("1678", "Guisantes", 50, "2 cucharadas"),
     ("1872", "Queso parmesano", 15, "rallado"), AJO, AOVE],
    ["Corta todas las verduras en juliana fina.",
     "Saltealas a fuego fuerte con el ajo, empezando por la zanahoria.",
     "Cuece la pasta al dente y mezclala con las verduras.",
     "Termina con el parmesano rallado."]),
 _r("E015", "Fideua de marisco sencilla", "media", 40,
    [("1117", "Fideos", 80, "1 plato en crudo"), ("817", "Gambas", 80, "unas unidades"),
     ("807", "Calamar", 80, "1 unidad"), CEB_S, ("1894", "Pimiento rojo", 50, "1/2"),
     ("1759", "Tomate frito", 60, "3 cucharadas"), ("1220", "Azafran", 1, "unas hebras"), AOVE],
    ["Sofrie la cebolla y el pimiento picados en la paellera.",
     "Añade el calamar en aros y dora 3 min. Incorpora el tomate.",
     "Añade los fideos y sofrielos 2 min removiendo.",
     "Cubre con caldo caliente y el azafran, y cuece 8 min.",
     "Coloca las gambas encima los ultimos 4 min y deja reposar."]),

 # ═══════════ ARROCES (12) ═══════════
 _r("E016", "Arroz a la cubana", "facil", 30,
    [ARROZ, ("545", "Huevo frito", 60, "1 unidad"), ("1759", "Tomate frito", 100, "1 vaso"),
     ("1737", "Platano", 100, "1 unidad"), AJO, AOVE],
    ["Cuece el arroz en agua con sal y un diente de ajo. Escurre.",
     "Calienta el tomate frito aparte.",
     "Frie el huevo en aceite bien caliente para que quede con puntilla.",
     "Frie el platano cortado por la mitad a lo largo hasta dorarlo.",
     "Sirve el arroz con el tomate, el huevo encima y el platano al lado."]),
 _r("E017", "Paella sencilla de pollo y verduras", "media", 45,
    [ARROZ, ("994", "Pechuga de pollo", 130, "1 filete"), ("1919", "Judias verdes", 70, "un puñado"),
     ("1894", "Pimiento rojo", 60, "1/2"), ("1759", "Tomate frito", 60, "3 cucharadas"),
     ("1220", "Azafran", 1, "unas hebras"), AJO, AOVE],
    ["Dora el pollo troceado en la paellera con el aceite y reserva.",
     "Sofrie el pimiento, las judias verdes y el ajo picado.",
     "Añade el tomate y sofrie 3 min.",
     "Incorpora el arroz y remueve 2 min para que se impregne.",
     "Añade el caldo caliente (doble volumen que arroz) con el azafran y el pollo.",
     "Cuece 10 min a fuego fuerte y 8 min a fuego suave, sin remover.",
     "Deja reposar 5 min tapado antes de servir."]),
 _r("E018", "Paella mixta sencilla", "media", 45,
    [ARROZ, ("994", "Pechuga de pollo", 90, "1/2 filete"), ("817", "Gambas", 80, "unas unidades"),
     ("1710", "Mejillones", 80, "unos pocos"), ("1894", "Pimiento rojo", 50, "1/2"),
     ("1759", "Tomate frito", 60, "3 cucharadas"), ("1220", "Azafran", 1, "unas hebras"), AOVE],
    ["Dora el pollo en la paellera y reserva.",
     "Sofrie el pimiento y añade el tomate.",
     "Incorpora el arroz, remueve y añade el caldo caliente con azafran.",
     "A los 10 min coloca las gambas y los mejillones por encima.",
     "Termina la coccion 8 min mas y deja reposar tapado."]),
 _r("E019", "Arroz caldoso de pollo y setas", "media", 40,
    [("1630", "Arroz", 70, "en crudo"), ("994", "Pechuga de pollo", 120, "1 filete"),
     ("2384", "Champiñones", 80, "unos pocos"), CEB_S, AJO, ("1759", "Tomate frito", 50, "2 cucharadas"), AOVE],
    ["Sofrie la cebolla y el ajo picados.",
     "Añade el pollo en dados y dora. Incorpora los champiñones laminados.",
     "Añade el tomate y el arroz, remueve 1 min.",
     "Cubre con caldo abundante (triple volumen) y cuece 18 min.",
     "Sirve caldoso, recien hecho."]),
 _r("E020", "Arroz negro con calamar", "media", 40,
    [ARROZ, ("807", "Calamar", 150, "1 unidad"), CEB_S, AJO, ("1894", "Pimiento rojo", 50, "1/2"),
     ("1759", "Tomate frito", 50, "2 cucharadas"), AOVE],
    ["Limpia y corta el calamar en aros; reserva la tinta o usa una bolsita.",
     "Sofrie la cebolla, el ajo y el pimiento picados.",
     "Añade el calamar y dora, luego el tomate.",
     "Incorpora el arroz, la tinta disuelta en caldo y cuece 18 min.",
     "Deja reposar 5 min antes de servir."]),
 _r("E021", "Arroz al horno con garbanzos", "media", 50,
    [ARROZ, ("1292", "Garbanzos cocidos", 120, "1/2 plato"), ("2403", "Patata", 100, "1 pequeña"),
     ("1879", "Tomate", 80, "1/2"), AJO2, ("400", "Pimenton", 2, "1 cucharadita"), AOVE],
    ["Frie las rodajas de patata y los ajos en una cazuela de barro.",
     "Añade el pimenton y el tomate, y sofrie brevemente.",
     "Incorpora el arroz y los garbanzos y remueve.",
     "Añade caldo caliente (doble volumen) y hornea 20 min a 200 grados."]),
 _r("E022", "Risotto de champiñones", "media", 35,
    [("1630", "Arroz", 80, "en crudo"), ("2384", "Champiñones", 120, "un buen puñado"),
     CEB_S, ("1872", "Queso parmesano", 25, "rallado"), ("2462", "Vino blanco", 30, "un chorro"), AOVE],
    ["Pocha la cebolla muy picada en el aceite sin que coja color.",
     "Añade los champiñones laminados y saltealos.",
     "Incorpora el arroz y nacaralo 2 min removiendo.",
     "Riega con el vino y deja evaporar.",
     "Añade caldo caliente cazo a cazo, removiendo, unos 18 min.",
     "Fuera del fuego, añade el parmesano y remueve para que quede cremoso."]),
 _r("E023", "Arroz tres delicias casero", "facil", 30,
    [ARROZ, ("2127", "Huevo", 60, "1 unidad"), ("965", "Jamon cocido", 50, "2 lonchas"),
     ("1678", "Guisantes", 50, "2 cucharadas"), ("1892", "Zanahoria", 50, "1/2"), AOVE_S],
    ["Cuece el arroz y escurrelo bien; deja que enfrie un poco.",
     "Haz una tortilla fina con el huevo y cortala en tiras.",
     "Saltea la zanahoria en dados y los guisantes.",
     "Añade el jamon en taquitos y el arroz, y saltea todo a fuego fuerte.",
     "Incorpora la tortilla en tiras y remueve."]),
 _r("E024", "Arroz con verduras y huevo escalfado", "facil", 30,
    [("904", "Arroz integral", 75, "en crudo"), ("1776", "Calabacin", 70, "1/2"),
     ("1894", "Pimiento rojo", 60, "1/2"), ("312", "Brocoli", 80, "unos ramilletes"),
     ("2127", "Huevo", 60, "1 unidad"), AJO, AOVE],
    ["Cuece el arroz integral 20 min.",
     "Saltea las verduras troceadas con el ajo a fuego fuerte.",
     "Escalfa el huevo en agua con un chorro de vinagre 3 min.",
     "Sirve el arroz con las verduras y el huevo encima."]),
 _r("E025", "Arroz con pollo al curry y verduras", "media", 35,
    [ARROZ, ("994", "Pechuga de pollo", 130, "1 filete"), CEBOLLA, ("1892", "Zanahoria", 50, "1/2"),
     ("1992", "Curry", 3, "1 cucharadita"), ("1694", "Leche entera", 70, "un chorro"), AOVE],
    ["Cuece el arroz y reserva.",
     "Pocha la cebolla y la zanahoria en dados.",
     "Añade el pollo en dados y dora.",
     "Espolvorea el curry, remueve y añade la leche. Deja espesar.",
     "Sirve sobre el arroz."]),
 _r("E026", "Arroz meloso de verduras y garbanzos", "facil", 35,
    [("1630", "Arroz", 75, "en crudo"), ("1921", "Berenjena", 70, "1/2"), ("1776", "Calabacin", 70, "1/2"),
     ("1894", "Pimiento rojo", 60, "1/2"), ("1292", "Garbanzos cocidos", 120, "1/2 plato"),
     ("1759", "Tomate frito", 60, "3 cucharadas"), AJO, AOVE],
    ["Sofrie el ajo y las verduras en dados hasta que esten tiernas.",
     "Añade el tomate y cocina 5 min.",
     "Incorpora el arroz y remueve 1 min.",
     "Añade caldo caliente (2,5 veces el volumen) y cuece 15 min removiendo.",
     "Incorpora los garbanzos los ultimos 3 min y sirve meloso."]),
 _r("E027", "Arroz con sepia y guisantes", "media", 40,
    [ARROZ, ("1854", "Sepia", 150, "1 unidad"), ("1678", "Guisantes", 60, "2 cucharadas"),
     CEB_S, AJO, ("1759", "Tomate frito", 50, "2 cucharadas"), AOVE],
    ["Sofrie la cebolla y el ajo. Añade la sepia en dados y dora.",
     "Incorpora el tomate y sofrie 3 min.",
     "Añade el arroz y los guisantes, remueve.",
     "Cubre con caldo caliente y cuece 18 min. Deja reposar."]),

 # ═══════════ POLLO (15) ═══════════
 _r("E028", "Pollo al ajillo con patatas", "media", 40,
    [("994", "Pechuga de pollo", 160, "en trozos"), ("2403", "Patata", 150, "1 mediana"),
     AJO2, ("2462", "Vino blanco", 40, "un chorro"), PEREJIL, AOVE],
    ["Corta el pollo en trozos y salpimenta.",
     "Frie las patatas en dados y reserva.",
     "Dora los ajos laminados en el aceite y añade el pollo.",
     "Cuando este dorado, riega con el vino y deja evaporar 5 min.",
     "Añade las patatas, espolvorea perejil y sirve."]),
 _r("E029", "Pollo asado al limon con verduras", "media", 50,
    [("994", "Pechuga de pollo", 170, "1 filete grueso"), ("2403", "Patata", 140, "1 mediana"),
     ("1892", "Zanahoria", 70, "1 unidad"), CEBOLLA, ("411", "Zumo de limon", 15, "1/2 limon"), AOVE],
    ["Coloca las verduras en rodajas en la bandeja del horno.",
     "Pon el pollo encima, riega con el aceite y el zumo de limon.",
     "Salpimenta y añade hierbas al gusto.",
     "Hornea 35 min a 190 grados, regando con los jugos a mitad."]),
 _r("E030", "Pechuga de pollo rellena de jamon y queso", "media", 35,
    [("994", "Pechuga de pollo", 150, "1 filete grueso"), ("965", "Jamon cocido", 30, "1 loncha"),
     ("1903", "Queso tierno", 30, "1 loncha"), ("2171", "Pan rallado", 20, "para rebozar"),
     ("2127", "Huevo", 30, "1/2 unidad"), ("1775", "Ensalada", 40, "de guarnicion"), AOVE],
    ["Abre la pechuga por la mitad sin llegar al final y salpimenta.",
     "Rellena con el jamon y el queso y cierra con palillos.",
     "Pasa por huevo batido y pan rallado.",
     "Dora en la sarten con aceite y termina 10 min en el horno a 180 grados.",
     "Sirve con la ensalada."]),
 _r("E031", "Pollo a la plancha con salsa de champiñones", "media", 30,
    [("994", "Pechuga de pollo", 150, "1 filete"), ("2384", "Champiñones", 100, "unos pocos"),
     CEB_S, ("1694", "Leche entera", 80, "un chorro"), ("2403", "Patata", 120, "1 pequeña"), AOVE],
    ["Cuece la patata y reserva.",
     "Haz el pollo a la plancha y resérvalo tapado.",
     "En la misma sarten, pocha la cebolla y los champiñones laminados.",
     "Añade la leche y deja reducir hasta que espese.",
     "Salsea el pollo y sirve con la patata."]),
 _r("E032", "Pollo al horno con miel y mostaza", "facil", 45,
    [("994", "Pechuga de pollo", 160, "1 filete"), ("2643", "Miel", 15, "1 cucharada"),
     ("1798", "Mostaza", 10, "1 cucharadita"), ("2403", "Patata", 150, "1 mediana"), AOVE],
    ["Mezcla la miel, la mostaza, el aceite, sal y pimienta.",
     "Unta el pollo con la mezcla y dejalo marinar 15 min.",
     "Coloca las patatas en gajos en la bandeja y el pollo encima.",
     "Hornea 30 min a 200 grados."]),
 _r("E033", "Pollo con verduras al wok", "facil", 25,
    [("994", "Pechuga de pollo", 140, "1 filete"), ("1894", "Pimiento rojo", 60, "1/2"),
     ("1776", "Calabacin", 70, "1/2"), ("1892", "Zanahoria", 50, "1/2"), ("2411", "Puerro", 50, "1/2"), AOVE],
    ["Corta todo en tiras finas del mismo tamaño.",
     "Calienta el wok al maximo con el aceite.",
     "Saltea el pollo 3 min y reserva.",
     "Saltea las verduras 4 min empezando por la zanahoria.",
     "Devuelve el pollo, remueve y sirve inmediatamente."]),
 _r("E034", "Pollo empanado con ensalada", "facil", 30,
    [("994", "Pechuga de pollo", 150, "1 filete"), ("2171", "Pan rallado", 30, "para rebozar"),
     ("2127", "Huevo", 40, "1 unidad"), LECHUGA, TOMATE, AOVE],
    ["Salpimenta los filetes de pollo.",
     "Pasalos por huevo batido y luego por pan rallado, presionando bien.",
     "Frielos en aceite caliente 3 min por lado hasta dorar.",
     "Escurre sobre papel y sirve con la ensalada aliñada."]),
 _r("E035", "Muslos de pollo guisados con patata", "media", 50,
    [("1388", "Muslo de pollo", 180, "1 unidad"), ("2403", "Patata", 150, "1 mediana"),
     CEBOLLA, ("1892", "Zanahoria", 60, "1/2"), ("2462", "Vino blanco", 40, "un chorro"), AJO, AOVE],
    ["Dora los muslos salpimentados en la cazuela y reserva.",
     "Pocha la cebolla, el ajo y la zanahoria.",
     "Riega con el vino y deja evaporar.",
     "Devuelve el pollo, añade la patata en trozos y cubre con caldo.",
     "Guisa 30 min a fuego lento hasta que la patata este tierna."]),
 _r("E036", "Pollo a la cerveza con arroz", "media", 40,
    [("994", "Pechuga de pollo", 150, "1 filete"), CEBOLLA, AJO,
     ("1630", "Arroz", 70, "en crudo"), ("2462", "Vino blanco", 50, "un chorro"), AOVE],
    ["Dora el pollo en trozos y reserva.",
     "Pocha la cebolla en juliana y el ajo.",
     "Devuelve el pollo, riega con el vino o cerveza y deja reducir 15 min.",
     "Sirve con el arroz blanco cocido."]),
 _r("E037", "Fajitas de pollo con pimientos", "media", 30,
    [("994", "Pechuga de pollo", 140, "1 filete"), ("1894", "Pimiento rojo", 70, "1/2"),
     ("1847", "Pimiento verde", 70, "1/2"), CEBOLLA, ("1792", "Tortillas de trigo", 60, "2 unidades"),
     ("400", "Pimenton", 2, "1 cucharadita"), AOVE],
    ["Corta el pollo y las verduras en tiras finas.",
     "Saltea el pollo con el pimenton, sal y pimienta.",
     "Añade los pimientos y la cebolla y saltea 5 min mas.",
     "Calienta las tortillas y rellenalas."]),
 _r("E038", "Pollo con salsa de tomate y albahaca", "facil", 30,
    [("994", "Pechuga de pollo", 150, "1 filete"), ("1759", "Tomate frito", 120, "1 vaso"),
     ("2510", "Queso mozzarella", 40, "para fundir"), ("1353", "Oregano", 1, "1 pizca"),
     ("1630", "Arroz", 60, "en crudo"), AOVE],
    ["Haz el pollo a la plancha y colocalo en una fuente.",
     "Cubrelo con el tomate y espolvorea oregano.",
     "Pon la mozzarella encima y gratina 8 min.",
     "Sirve con el arroz blanco."]),
 _r("E039", "Pollo teriyaki casero con arroz", "media", 30,
    [("994", "Pechuga de pollo", 150, "1 filete"), ARROZ, ("2643", "Miel", 12, "1 cucharada"),
     ("312", "Brocoli", 90, "unos ramilletes"), AJO, AOVE_S],
    ["Cuece el arroz y el brocoli al vapor.",
     "Corta el pollo en dados y dorarlo en la sarten.",
     "Añade una mezcla de salsa de soja, miel y ajo rallado.",
     "Deja que reduzca hasta glasear el pollo.",
     "Sirve sobre el arroz con el brocoli."]),
 _r("E040", "Alitas de pollo al horno con patatas", "facil", 50,
    [("1388", "Alitas de pollo", 180, "varias"), ("2403", "Patata", 150, "1 mediana"),
     ("400", "Pimenton", 2, "1 cucharadita"), AJO2, AOVE],
    ["Adoba las alitas con ajo picado, pimenton, sal, pimienta y aceite.",
     "Deja reposar 20 min.",
     "Coloca en la bandeja con las patatas en gajos.",
     "Hornea 35 min a 200 grados dandoles la vuelta a mitad."]),
 _r("E041", "Ensalada cesar con pollo", "facil", 25,
    [("994", "Pechuga de pollo", 130, "1 filete"), ("1775", "Lechuga romana", 70, "varias hojas"),
     ("1792", "Pan (picatostes)", 30, "1 rebanada"), ("1872", "Queso parmesano", 20, "en lascas"),
     ("1929", "Mayonesa ligera", 20, "1 cucharada"), AOVE],
    ["Haz el pollo a la plancha y cortalo en tiras.",
     "Tuesta el pan en dados con un poco de aceite para los picatostes.",
     "Mezcla la mayonesa con unas gotas de limon y mostaza para la salsa.",
     "Monta la lechuga, el pollo, los picatostes y el parmesano, y aliña."]),
 _r("E042", "Pollo con pisto manchego", "media", 40,
    [("994", "Pechuga de pollo", 150, "1 filete"), ("1921", "Berenjena", 70, "1/2"),
     ("1776", "Calabacin", 70, "1/2"), ("1894", "Pimiento rojo", 60, "1/2"), CEB_S,
     ("1759", "Tomate frito", 80, "1/2 vaso"), AOVE],
    ["Corta todas las verduras en dados pequeños del mismo tamaño.",
     "Pocha la cebolla y el pimiento 10 min.",
     "Añade el calabacin y la berenjena y cocina 15 min mas.",
     "Incorpora el tomate y deja 5 min.",
     "Haz el pollo a la plancha y sirvelo sobre el pisto."]),

 # ═══════════ SANDWICHES (10) ═══════════
 _r("E043", "Sandwich mixto de jamon y queso", "facil", 10,
    [PAN_MOL, ("965", "Jamon cocido", 50, "2 lonchas"), ("1903", "Queso tierno", 40, "2 lonchas"), AOVE_S],
    ["Unta ligeramente el pan con aceite por fuera.",
     "Monta el sandwich con el jamon y el queso dentro.",
     "Tuestalo en la sandwichera o sarten hasta que el queso funda."]),
 _r("E044", "Sandwich club de pollo y bacon", "media", 20,
    [("1792", "Pan de molde", 90, "3 rebanadas"), ("994", "Pechuga de pollo", 90, "1/2 filete"),
     ("602", "Bacon", 25, "2 tiras"), LECHUGA, TOMATE, ("1929", "Mayonesa ligera", 15, "1 cucharada")],
    ["Tuesta las tres rebanadas de pan.",
     "Haz el pollo a la plancha en filetes finos y dora el bacon.",
     "Unta mayonesa y monta dos pisos: pollo con lechuga, y bacon con tomate.",
     "Corta en triangulos y sujeta con palillos."]),
 _r("E045", "Sandwich vegetal con atun", "facil", 12,
    [PAN_INT, ("2131", "Atun en aceite (escurrido)", 60, "1/2 lata"), ("2126", "Huevo cocido", 50, "1 unidad"),
     LECHUGA, TOMATE, ("1929", "Mayonesa ligera", 15, "1 cucharada")],
    ["Cuece el huevo 10 min y cortalo en rodajas.",
     "Mezcla el atun escurrido con un poco de mayonesa.",
     "Tuesta el pan y monta con lechuga, tomate, huevo y atun."]),
 _r("E046", "Sandwich de pavo, queso y aguacate", "facil", 10,
    [PAN_INT, ("1371", "Pavo (fiambre)", 50, "2 lonchas"), ("1903", "Queso tierno", 30, "1 loncha"),
     ("1623", "Aguacate", 50, "1/3"), LECHUGA],
    ["Tuesta el pan.",
     "Machaca el aguacate con sal y untalo.",
     "Monta con el pavo, el queso y la lechuga."]),
 _r("E047", "Sandwich caliente de pollo y pimientos", "facil", 18,
    [PAN_MOL, ("994", "Pechuga de pollo", 100, "1/2 filete"), ("1894", "Pimiento rojo", 60, "1/2"),
     ("1903", "Queso tierno", 30, "1 loncha"), AOVE_S],
    ["Asa el pimiento en tiras con un poco de aceite.",
     "Haz el pollo a la plancha en filetes finos.",
     "Monta el sandwich con el queso y tuestalo hasta que funda."]),
 _r("E048", "Sandwich de tortilla francesa", "facil", 12,
    [PAN_MOL, ("2127", "Huevo", 90, "1 y 1/2"), ("1903", "Queso tierno", 25, "1 loncha"), AOVE_S],
    ["Bate los huevos con sal y cuaja una tortilla fina del tamaño del pan.",
     "Coloca el queso sobre la tortilla caliente para que funda.",
     "Monta el sandwich y tuestalo ligeramente."]),
 _r("E049", "Sandwich de salmon ahumado y queso fresco", "facil", 10,
    [PAN_INT, ("2626", "Salmon ahumado", 50, "unas lonchas"), ("1794", "Queso fresco", 40, "para untar"),
     ("2407", "Pepino", 40, "unas rodajas"), ("411", "Zumo de limon", 5, "unas gotas")],
    ["Tuesta el pan y untalo con el queso fresco.",
     "Coloca el salmon y el pepino en rodajas finas.",
     "Termina con unas gotas de limon y pimienta negra."]),
 _r("E050", "Sandwich de pollo al curry", "facil", 15,
    [PAN_INT, ("994", "Pechuga de pollo", 100, "1/2 filete"), ("1929", "Mayonesa ligera", 20, "1 cucharada"),
     ("1992", "Curry", 2, "1 pizca"), LECHUGA],
    ["Cuece o haz a la plancha el pollo y desmenuzalo.",
     "Mezclalo con la mayonesa y el curry.",
     "Tuesta el pan y monta con la lechuga."]),
 _r("E051", "Sandwich caprese", "facil", 10,
    [PAN_INT, ("2510", "Queso mozzarella", 60, "unas rodajas"), TOMATE,
     ("1353", "Oregano", 1, "1 pizca"), AOVE_S],
    ["Corta la mozzarella y el tomate en rodajas.",
     "Monta el sandwich alternandolos.",
     "Riega con aceite, oregano, sal y pimienta.",
     "Tuestalo ligeramente en la plancha."]),
 _r("E052", "Sandwich de pollo, queso fundido y champiñones", "facil", 20,
    [PAN_MOL, ("994", "Pechuga de pollo", 100, "1/2 filete"), ("2384", "Champiñones", 80, "unos pocos"),
     ("940", "Queso fundido", 40, "2 lonchas"), AJO, AOVE_S],
    ["Saltea los champiñones laminados con el ajo hasta dorar.",
     "Haz el pollo a la plancha en filetes finos y salpimenta.",
     "Monta el sandwich con el queso, el pollo y los champiñones.",
     "Tuestalo hasta que el queso se derrita."]),

 # ═══════════ BOCADILLOS (10) ═══════════
 _r("E053", "Bocadillo de tortilla de patatas", "media", 35,
    [PAN_BAR, ("2127", "Huevo", 100, "2 unidades"), ("2403", "Patata", 120, "1 pequeña"),
     CEB_S, AOVE],
    ["Frie la patata y la cebolla en laminas a fuego medio hasta que esten blandas.",
     "Bate los huevos, mezcla con la patata escurrida y cuaja la tortilla.",
     "Abre el pan y rellenalo con un buen trozo de tortilla."]),
 _r("E054", "Bocadillo de jamon serrano con tomate", "facil", 8,
    [PAN_BAR, ("1814", "Jamon serrano", 50, "unas lonchas"), TOMATE, AOVE],
    ["Abre el pan y tuestalo ligeramente.",
     "Ralla el tomate y extiendelo sobre el pan con un chorro de aceite y sal.",
     "Coloca el jamon serrano por encima."]),
 _r("E055", "Bocadillo de calamares", "media", 25,
    [PAN_BAR, ("807", "Calamar", 130, "en aros"), ("2171", "Harina/pan rallado", 25, "para rebozar"),
     ("411", "Zumo de limon", 5, "unas gotas"), AOVE],
    ["Corta el calamar en aros y salalo.",
     "Pasalo por harina sacudiendo el exceso.",
     "Frie en aceite muy caliente 2 min hasta dorar.",
     "Escurre sobre papel y sirve en el pan con unas gotas de limon."]),
 _r("E056", "Bocadillo de lomo con queso", "facil", 20,
    [PAN_BAR, ("2259", "Lomo de cerdo", 120, "2 filetes"), ("1903", "Queso tierno", 35, "1 loncha"), AOVE_S],
    ["Haz los filetes de lomo a la plancha, salpimentados.",
     "Pon el queso encima al final para que funda.",
     "Monta el bocadillo con el pan ligeramente tostado."]),
 _r("E057", "Bocadillo de pollo a la plancha con lechuga", "facil", 20,
    [PAN_BAR, ("994", "Pechuga de pollo", 130, "1 filete"), LECHUGA, TOMATE,
     ("1929", "Mayonesa ligera", 15, "1 cucharada")],
    ["Haz la pechuga a la plancha en filetes finos.",
     "Unta el pan con la mayonesa.",
     "Monta con la lechuga, el tomate en rodajas y el pollo."]),
 _r("E058", "Bocadillo de atun con pimientos", "facil", 12,
    [PAN_BAR, ("2131", "Atun en aceite (escurrido)", 70, "1 lata"), ("1894", "Pimiento rojo asado", 60, "unas tiras"),
     ("2126", "Huevo cocido", 40, "1/2 unidad"), AOVE_S],
    ["Asa el pimiento en tiras (o usa de conserva).",
     "Escurre bien el atun.",
     "Monta el bocadillo con el pimiento, el atun y el huevo en rodajas."]),
 _r("E059", "Bocadillo de chorizo a la plancha", "facil", 15,
    [PAN_BAR, ("1661", "Chorizo", 60, "unas rodajas"), ("1894", "Pimiento rojo", 50, "1/2"), AOVE_S],
    ["Haz el chorizo en rodajas a la plancha hasta que suelte su grasa.",
     "Asa el pimiento en tiras en la misma sarten.",
     "Monta el bocadillo bien caliente."]),
 _r("E060", "Bocadillo vegetal completo", "facil", 15,
    [PAN_BAR, ("2126", "Huevo cocido", 50, "1 unidad"), ("2131", "Atun en aceite (escurrido)", 50, "1/2 lata"),
     LECHUGA, TOMATE, ("1929", "Mayonesa ligera", 15, "1 cucharada")],
    ["Cuece el huevo y cortalo en rodajas.",
     "Monta el pan con lechuga, tomate, huevo y atun.",
     "Termina con un poco de mayonesa."]),
 _r("E061", "Bocadillo de pavo, queso y aguacate", "facil", 12,
    [PAN_BAR, ("1371", "Pavo (fiambre)", 60, "unas lonchas"), ("1903", "Queso tierno", 30, "1 loncha"),
     ("1623", "Aguacate", 50, "1/3"), LECHUGA],
    ["Machaca el aguacate y untalo en el pan.",
     "Monta con el pavo, el queso y la lechuga."]),
 _r("E062", "Bocadillo de sardinas y pimiento", "facil", 15,
    [PAN_BAR, ("2630", "Sardinas", 90, "unas unidades"), ("1894", "Pimiento rojo", 60, "1/2"),
     TOMATE, AOVE_S],
    ["Asa las sardinas en la plancha.",
     "Asa el pimiento en tiras.",
     "Monta el bocadillo con el tomate rallado, el pimiento y las sardinas."]),

 # ═══════════ VERDURAS (18) ═══════════
 _r("E063", "Pisto manchego con huevo", "media", 40,
    [("1921", "Berenjena", 100, "1/2"), ("1776", "Calabacin", 100, "1/2"),
     ("1894", "Pimiento rojo", 80, "1 unidad"), CEBOLLA, ("1759", "Tomate frito", 100, "1 vaso"),
     ("2127", "Huevo", 60, "1 unidad"), AOVE],
    ["Corta todas las verduras en dados regulares.",
     "Pocha la cebolla y el pimiento 10 min a fuego suave.",
     "Añade el calabacin y la berenjena y cocina 20 min removiendo.",
     "Incorpora el tomate y deja 5 min mas.",
     "Sirve con un huevo frito o escalfado encima."]),
 _r("E064", "Menestra de verduras con jamon", "media", 35,
    [("1919", "Judias verdes", 80, "un puñado"), ("1892", "Zanahoria", 70, "1 unidad"),
     ("1678", "Guisantes", 60, "2 cucharadas"), ("1176", "Alcachofas", 80, "2 unidades"),
     ("1814", "Jamon serrano", 30, "en taquitos"), AJO, AOVE],
    ["Cuece las verduras por separado para que cada una quede en su punto.",
     "Dora el ajo laminado y el jamon en taquitos.",
     "Añade las verduras escurridas y saltea todo junto 3 min.",
     "Rectifica de sal y sirve."]),
 _r("E065", "Berenjenas rellenas de verduras y queso", "media", 45,
    [("1921", "Berenjena", 200, "1 unidad"), ("1776", "Calabacin", 60, "1/2"),
     ("1894", "Pimiento rojo", 50, "1/2"), CEB_S, ("1759", "Tomate frito", 60, "3 cucharadas"),
     ("2510", "Queso mozzarella", 40, "para gratinar"), AOVE],
    ["Corta la berenjena por la mitad, haz cortes en la pulpa y hornea 20 min a 200 grados.",
     "Retira la pulpa dejando las paredes y pícala.",
     "Sofrie la cebolla, el pimiento, el calabacin y la pulpa.",
     "Añade el tomate y rellena las berenjenas.",
     "Cubre con queso y gratina 10 min."]),
 _r("E066", "Espinacas a la crema con picatostes", "facil", 25,
    [("2395", "Espinacas", 200, "3 puñados"), ("1694", "Leche entera", 100, "1/2 vaso"),
     AJO, ("1792", "Pan (picatostes)", 30, "1 rebanada"), ("1901", "Queso curado", 20, "rallado"), AOVE],
    ["Saltea las espinacas con el ajo hasta que reduzcan y escurre el agua.",
     "Añade la leche y deja reducir a fuego suave.",
     "Tuesta el pan en dados con aceite.",
     "Sirve con el queso rallado y los picatostes."]),
 _r("E067", "Parrillada de verduras con queso a la plancha", "facil", 30,
    [("1776", "Calabacin", 90, "1/2"), ("1921", "Berenjena", 90, "1/2"),
     ("1894", "Pimiento rojo", 80, "1 unidad"), CEBOLLA, ("151", "Esparragos", 70, "unos pocos"),
     ("1794", "Queso fresco", 120, "1 tarrina"), AOVE],
    ["Corta las verduras en laminas de 1 cm.",
     "Pincelalas con aceite y sal.",
     "Asalas en la plancha bien caliente por ambos lados.",
     "Marca el queso fresco en rodajas gruesas en la misma plancha.",
     "Sirve todo junto con una vinagreta de aceite, vinagre y ajo picado."]),
 _r("E068", "Crema de calabaza con huevo poche y jamon", "facil", 30,
    [("1920", "Calabaza", 250, "un trozo grande"), ("1892", "Zanahoria", 80, "1 unidad"),
     ("2411", "Puerro", 60, "1/2"), ("2403", "Patata", 60, "1/2 pequeña"),
     ("2127", "Huevo", 60, "1 unidad"), ("1814", "Jamon serrano", 30, "en virutas"), AOVE],
    ["Trocea todas las verduras.",
     "Pochalas en la olla con el aceite 5 min.",
     "Cubre con agua o caldo y cuece 20 min.",
     "Tritura hasta obtener una crema fina y rectifica de sal.",
     "Escalfa el huevo 3 min y crujiente el jamon en la sarten.",
     "Sirve la crema con el huevo en el centro y el jamon por encima."]),
 _r("E069", "Judias verdes con patata, huevo y jamon", "facil", 30,
    [("1919", "Judias verdes", 200, "2 puñados"), ("2403", "Patata", 150, "1 mediana"),
     ("2126", "Huevo cocido", 60, "1 unidad"), ("1814", "Jamon serrano", 35, "en taquitos"),
     AJO2, ("400", "Pimenton", 2, "1 cucharadita"), AOVE],
    ["Cuece las judias y la patata en trozos 15 min. Cuece tambien el huevo.",
     "Escurre las verduras y reserva.",
     "Dora los ajos laminados y el jamon en taquitos.",
     "Retira del fuego, añade el pimenton y riega las verduras con este refrito.",
     "Sirve con el huevo cocido en cuartos."]),
 _r("E070", "Revuelto de esparragos y gambas", "facil", 20,
    [("151", "Esparragos verdes", 120, "1 manojo"), ("817", "Gambas", 90, "un puñado"),
     ("2127", "Huevo", 100, "2 unidades"), AJO, AOVE],
    ["Trocea los esparragos y saltealos con el ajo hasta que esten tiernos.",
     "Añade las gambas peladas y saltea 2 min.",
     "Incorpora los huevos batidos y remueve a fuego suave hasta cuajar cremoso."]),
 _r("E071", "Coliflor gratinada con bechamel", "media", 40,
    [("2387", "Coliflor", 250, "1 plato"), ("1694", "Leche entera", 120, "1/2 vaso"),
     ("1901", "Queso curado", 35, "rallado"), AOVE],
    ["Cuece la coliflor en ramilletes 12 min y escurre bien.",
     "Prepara una bechamel ligera con el aceite, una cucharada de harina y la leche.",
     "Coloca la coliflor en la fuente y cubre con la bechamel.",
     "Espolvorea queso y gratina 10 min."]),
 _r("E072", "Alcachofas salteadas con jamon", "media", 30,
    [("1176", "Alcachofas", 200, "4 unidades"), ("1814", "Jamon serrano", 35, "en taquitos"),
     AJO2, ("2462", "Vino blanco", 30, "un chorro"), AOVE],
    ["Limpia las alcachofas y cortalas en cuartos; cuecelas 10 min.",
     "Dora los ajos y el jamon en taquitos.",
     "Añade las alcachofas escurridas y saltea hasta dorar.",
     "Riega con el vino y deja evaporar."]),
 _r("E073", "Escalivada con anchoas", "facil", 50,
    [("1921", "Berenjena", 150, "1 unidad"), ("1894", "Pimiento rojo", 120, "1 unidad"),
     CEBOLLA, ("2630", "Anchoas/sardinas", 40, "unos filetes"), AOVE],
    ["Asa la berenjena, el pimiento y la cebolla enteros al horno 40 min a 200 grados.",
     "Deja templar, pelalos y cortalos en tiras.",
     "Aliña con aceite y sal.",
     "Sirve con los filetes de anchoa por encima."]),
 _r("E074", "Salteado de brocoli, ajo y almendras", "facil", 20,
    [("312", "Brocoli", 220, "1 arbol pequeño"), AJO2, ("896", "Almendras", 20, "un puñado"),
     ("400", "Pimenton", 1, "1 pizca"), AOVE],
    ["Cuece el brocoli al vapor 6 min para que quede al dente.",
     "Dora los ajos laminados y las almendras en el aceite.",
     "Añade el brocoli y saltea 3 min.",
     "Espolvorea el pimenton fuera del fuego."]),
 _r("E075", "Calabacines rellenos de carne", "media", 45,
    [("1776", "Calabacin", 200, "1 unidad grande"), ("1931", "Carne picada de ternera", 100, "1 puñado"),
     CEB_S, ("1759", "Tomate frito", 60, "3 cucharadas"), ("1901", "Queso curado", 30, "rallado"), AOVE],
    ["Corta los calabacines por la mitad y vacialos con cuidado.",
     "Pica la pulpa y pochala con la cebolla.",
     "Añade la carne, dorala e incorpora el tomate.",
     "Rellena los calabacines, cubre con queso y hornea 25 min a 190 grados."]),
 _r("E076", "Puré de patata y verduras con huevo", "facil", 30,
    [("2403", "Patata", 200, "1 grande"), ("1892", "Zanahoria", 80, "1 unidad"),
     ("2127", "Huevo", 60, "1 unidad"), ("1694", "Leche entera", 60, "un chorro"), AOVE],
    ["Cuece la patata y la zanahoria hasta que esten muy tiernas.",
     "Machacalas con la leche y un poco de aceite hasta obtener un pure fino.",
     "Escalfa o cuece el huevo.",
     "Sirve el pure con el huevo encima y pimienta negra."]),
 _r("E077", "Ratatouille al horno", "media", 55,
    [("1921", "Berenjena", 120, "1/2"), ("1776", "Calabacin", 120, "1/2"), TOMATE,
     ("1894", "Pimiento rojo", 70, "1/2"), CEB_S, ("1353", "Oregano", 1, "1 pizca"),
     ("2510", "Queso mozzarella", 80, "para gratinar"), AOVE],
    ["Prepara una base sofriendo la cebolla, el pimiento y parte del tomate.",
     "Corta el calabacin, la berenjena y el tomate en rodajas finas.",
     "Colocalas en pie alternando colores sobre la base.",
     "Riega con aceite, sal y oregano.",
     "Hornea 40 min a 180 grados tapado con papel.",
     "Destapa, reparte la mozzarella y gratina 8 min mas."]),
 _r("E078", "Setas al ajillo con huevo poche", "facil", 20,
    [("2384", "Setas/champiñones", 200, "un buen puñado"), AJO2, ("2127", "Huevo", 60, "1 unidad"),
     PEREJIL, AOVE],
    ["Limpia y trocea las setas.",
     "Dora los ajos laminados en el aceite.",
     "Añade las setas y saltea a fuego fuerte hasta que evaporen el agua.",
     "Escalfa el huevo 3 min y sirvelo sobre las setas con perejil."]),
 _r("E079", "Ensalada templada de verduras asadas y queso", "facil", 35,
    [("1894", "Pimiento rojo", 90, "1 unidad"), ("1776", "Calabacin", 80, "1/2"), CEB_S,
     ("1794", "Queso fresco", 60, "en dados"), ("1775", "Rucula/lechuga", 40, "unas hojas"),
     ("2201", "Nueces", 15, "2 nueces"), AOVE],
    ["Asa el pimiento, el calabacin y la cebolla en tiras 25 min a 200 grados.",
     "Monta la base de hojas verdes.",
     "Coloca las verduras templadas encima con el queso en dados.",
     "Termina con las nueces y una vinagreta."]),
 _r("E080", "Tortilla de calabacin y cebolla", "facil", 30,
    [("2127", "Huevo", 120, "2 unidades"), ("1776", "Calabacin", 150, "1 unidad"),
     CEBOLLA, ("1775", "Ensalada", 40, "de guarnicion"), AOVE],
    ["Pocha el calabacin y la cebolla en laminas a fuego medio 15 min.",
     "Escurre bien el aceite sobrante.",
     "Bate los huevos, mezcla con la verdura y sazona.",
     "Cuaja la tortilla por ambos lados y sirve con ensalada."]),

 # ═══════════ PESCADOS Y MARISCOS (10) ═══════════
 _r("E081", "Merluza en salsa verde con almejas", "media", 30,
    [("2347", "Merluza", 180, "1 rodaja"), ("1710", "Almejas", 80, "unas pocas"),
     AJO2, PEREJIL, ("2462", "Vino blanco", 40, "un chorro"), ("1678", "Guisantes", 50, "2 cucharadas"), AOVE],
    ["Dora los ajos picados en una cazuela de barro sin quemarlos.",
     "Añade una cucharadita de harina y remueve.",
     "Incorpora el vino y un poco de caldo, moviendo la cazuela para ligar.",
     "Coloca la merluza, las almejas y los guisantes.",
     "Cocina 8 min moviendo la cazuela, y termina con perejil."]),
 _r("E082", "Bacalao al pil pil con patatas", "alta", 35,
    [("1915", "Bacalao", 180, "1 lomo"), AJO2, ("2403", "Patata", 150, "1 mediana"),
     ("2544", "Aceite de oliva virgen extra", 20, "2 cucharadas")],
    ["Confita los ajos laminados en el aceite a fuego muy suave y reserva.",
     "Pon el bacalao con la piel hacia abajo y cocinalo 5 min a fuego bajo.",
     "Retira el bacalao y deja templar el aceite.",
     "Liga la salsa moviendo la cazuela en circulos hasta que emulsione.",
     "Sirve con las patatas panadera."]),
 _r("E083", "Salmon al horno con verduras", "facil", 30,
    [("2626", "Salmon", 170, "1 lomo"), ("1776", "Calabacin", 80, "1/2"),
     ("1894", "Pimiento rojo", 70, "1/2"), CEB_S, ("411", "Zumo de limon", 10, "1/2 limon"), AOVE],
    ["Coloca las verduras en juliana en la bandeja y hornea 15 min a 190 grados.",
     "Pon el salmon encima, riega con limon y aceite.",
     "Hornea 12 min mas hasta que el salmon este jugoso."]),
 _r("E084", "Marmitako de bonito", "media", 45,
    [("800", "Bonito", 160, "1 rodaja"), ("2403", "Patata", 180, "1 grande"),
     ("1894", "Pimiento rojo", 70, "1/2"), CEBOLLA, ("400", "Pimenton", 2, "1 cucharadita"), AOVE],
    ["Pocha la cebolla y el pimiento picados 10 min.",
     "Añade el pimenton y remueve rapido fuera del fuego.",
     "Incorpora las patatas cascadas (rompiendolas con el cuchillo).",
     "Cubre con caldo y cuece 20 min hasta que la patata este tierna.",
     "Apaga el fuego, añade el bonito en dados y deja 3 min con el calor residual."]),
 _r("E085", "Calamares en su tinta con arroz", "alta", 45,
    [("807", "Calamar", 180, "1 unidad"), CEBOLLA, AJO, ("1759", "Tomate frito", 50, "2 cucharadas"),
     ("1630", "Arroz", 60, "en crudo"), AOVE],
    ["Limpia los calamares y cortalos en aros.",
     "Pocha la cebolla y el ajo muy picados hasta que esten dorados.",
     "Añade el tomate y los calamares.",
     "Incorpora la tinta disuelta en un poco de agua y guisa 25 min a fuego lento.",
     "Sirve con el arroz blanco."]),
 _r("E086", "Gambas al ajillo con pan", "facil", 15,
    [("817", "Gambas", 150, "1 plato"), AJO2, ("2544", "Aceite de oliva virgen extra", 15, "1,5 cucharadas"),
     ("1810", "Pan", 50, "para mojar"), PEREJIL],
    ["Calienta el aceite en una cazuela de barro con los ajos laminados y guindilla.",
     "Cuando el ajo empiece a dorarse, añade las gambas peladas.",
     "Saltea 2 min a fuego fuerte, sin pasarlas.",
     "Espolvorea perejil y sirve con pan para mojar."]),
 _r("E087", "Dorada a la espalda con patatas", "media", 35,
    [("2029", "Dorada", 200, "1 unidad"), ("2403", "Patata", 150, "1 mediana"),
     AJO2, ("411", "Zumo de limon", 10, "1/2 limon"), AOVE],
    ["Corta las patatas en rodajas finas y asalas 20 min a 200 grados.",
     "Abre la dorada por la mitad, salala y colocala sobre las patatas.",
     "Hornea 12 min.",
     "Dora los ajos laminados en el aceite con un chorro de vinagre y riega el pescado."]),
 _r("E088", "Mejillones a la marinera", "facil", 25,
    [("1710", "Mejillones", 250, "1 plato"), CEB_S, AJO, ("1759", "Tomate frito", 50, "2 cucharadas"),
     ("2462", "Vino blanco", 50, "un chorro"), ("1810", "Pan", 40, "para mojar"), AOVE],
    ["Limpia bien los mejillones raspando las conchas.",
     "Pocha la cebolla y el ajo muy picados.",
     "Añade el tomate y el vino, y deja evaporar el alcohol.",
     "Incorpora los mejillones, tapa y cocina 5 min hasta que abran.",
     "Sirve con la salsa y pan."]),
 _r("E089", "Rape a la plancha con verduras al vapor", "media", 30,
    [("2623", "Rape", 180, "1 rodaja"), ("312", "Brocoli", 90, "unos ramilletes"),
     ("1892", "Zanahoria", 60, "1/2"), ("1919", "Judias verdes", 70, "un puñado"), AJO, AOVE],
    ["Cuece las verduras al vapor 8 min para que queden al dente.",
     "Salpimenta el rape y hazlo a la plancha 4 min por lado.",
     "Dora el ajo laminado en el aceite y riega el pescado y las verduras."]),
 _r("E090", "Pulpo a la gallega", "media", 50,
    [("1738", "Pulpo", 200, "1 pata"), ("2403", "Patata", 180, "1 grande"),
     ("400", "Pimenton", 3, "1 cucharadita"), ("2544", "Aceite de oliva virgen extra", 15, "1,5 cucharadas")],
    ["Cuece el pulpo asustandolo tres veces en agua hirviendo, luego 35 min.",
     "Cuece las patatas en la misma agua.",
     "Corta el pulpo en rodajas con tijeras.",
     "Sirve sobre las patatas en rodajas.",
     "Espolvorea sal gorda y pimenton, y riega con aceite."]),

 # ═══════════ CARNES Y LEGUMBRES (10) ═══════════
 _r("E091", "Albondigas en salsa con patatas", "media", 45,
    [("1931", "Carne picada de ternera", 130, "para las albondigas"), ("2171", "Pan rallado", 15, "1 cucharada"),
     ("2127", "Huevo", 25, "1/2 unidad"), CEBOLLA, ("1892", "Zanahoria", 50, "1/2"),
     ("2403", "Patata", 120, "1 pequeña"), AJO, AOVE],
    ["Mezcla la carne con el huevo, el pan rallado, ajo y perejil picados.",
     "Forma las albondigas y dóralas en la sarten. Reserva.",
     "Pocha la cebolla y la zanahoria, y tritura con un poco de caldo para la salsa.",
     "Devuelve las albondigas a la salsa y guisa 15 min.",
     "Sirve con las patatas."]),
 _r("E092", "Lentejas estofadas con chorizo", "media", 45,
    [("1126", "Lentejas cocidas", 200, "1 plato"), ("1661", "Chorizo", 40, "unas rodajas"),
     ("2403", "Patata", 80, "1/2 pequeña"), ("1892", "Zanahoria", 60, "1/2"), CEB_S,
     ("400", "Pimenton", 2, "1 cucharadita"), AOVE],
    ["Pocha la cebolla y la zanahoria picadas.",
     "Añade el chorizo en rodajas y dora 2 min.",
     "Incorpora el pimenton fuera del fuego para que no se queme.",
     "Añade las lentejas, la patata en trozos y caldo.",
     "Guisa 20 min a fuego lento hasta que espese."]),
 _r("E093", "Garbanzos con espinacas y huevo", "media", 30,
    [("1292", "Garbanzos cocidos", 200, "1 plato"), ("2395", "Espinacas", 150, "2 puñados"),
     ("2126", "Huevo cocido", 60, "1 unidad"), AJO2, ("400", "Pimenton", 2, "1 cucharadita"),
     ("1810", "Pan", 20, "1 rebanada"), AOVE],
    ["Frie el pan y los ajos, y tritúralos con un poco de caldo (majado).",
     "Saltea las espinacas hasta que reduzcan.",
     "Añade los garbanzos, el majado y el pimenton.",
     "Cocina 10 min y sirve con el huevo cocido en cuartos."]),
 _r("E094", "Fabada ligera de alubias", "media", 50,
    [("898", "Alubias blancas cocidas", 220, "1 plato"), ("1661", "Chorizo", 40, "unas rodajas"),
     CEB_S, AJO, ("400", "Pimenton", 2, "1 cucharadita"), AOVE],
    ["Pocha la cebolla y el ajo picados.",
     "Añade el chorizo en rodajas y dora.",
     "Incorpora el pimenton fuera del fuego.",
     "Añade las alubias con su caldo y guisa 25 min a fuego muy suave.",
     "Menea la cazuela de vez en cuando para que ligue."]),
 _r("E095", "Solomillo de cerdo a la mostaza con pure", "media", 35,
    [("1021", "Solomillo de cerdo", 160, "1 unidad"), ("1798", "Mostaza", 12, "1 cucharadita"),
     ("1694", "Leche entera", 70, "un chorro"), ("2403", "Patata", 180, "1 grande"), AOVE],
    ["Cuece la patata y haz un pure con un poco de leche y aceite.",
     "Marca el solomillo en medallones a fuego fuerte y reserva.",
     "En la misma sarten, añade la mostaza y la leche y deja reducir.",
     "Devuelve la carne a la salsa 2 min y sirve sobre el pure."]),
 _r("E096", "Ternera guisada con verduras", "media", 60,
    [("981", "Ternera (solomillo)", 160, "en dados"), ("2403", "Patata", 150, "1 mediana"),
     ("1892", "Zanahoria", 70, "1 unidad"), CEBOLLA, ("2462", "Vino blanco", 50, "un chorro"), AJO, AOVE],
    ["Salpimenta la carne en dados y dorala a fuego fuerte. Reserva.",
     "Pocha la cebolla, el ajo y la zanahoria.",
     "Riega con el vino y deja evaporar.",
     "Devuelve la carne, cubre con caldo y guisa 40 min a fuego lento.",
     "Añade la patata los ultimos 20 min."]),
 _r("E097", "Cerdo agridulce con arroz", "media", 35,
    [("2259", "Lomo de cerdo", 150, "en dados"), ARROZ, ("1894", "Pimiento rojo", 70, "1/2"),
     ("1962", "Piña", 60, "unos trozos"), ("2643", "Miel", 12, "1 cucharada"), AOVE],
    ["Cuece el arroz y reserva.",
     "Dora el cerdo en dados a fuego fuerte.",
     "Añade el pimiento en tiras y saltea.",
     "Incorpora la piña, la miel y un chorro de vinagre y salsa de soja.",
     "Deja reducir hasta que glasee y sirve con el arroz."]),
 _r("E098", "Hamburguesa casera completa con patatas", "media", 30,
    [("2174", "Pan de hamburguesa", 80, "1 unidad"), ("1931", "Carne picada de ternera", 130, "1 hamburguesa"),
     ("1903", "Queso tierno", 30, "1 loncha"), LECHUGA, TOMATE, ("2403", "Patata", 120, "1 pequeña"), AOVE],
    ["Sazona la carne y forma la hamburguesa sin apretarla demasiado.",
     "Corta las patatas en gajos y asalas 25 min a 200 grados.",
     "Haz la hamburguesa a la plancha 3-4 min por lado.",
     "Funde el queso encima al final.",
     "Monta el pan tostado con lechuga, tomate y la carne."]),
 _r("E099", "Pavo en salsa de almendras", "media", 35,
    [("1371", "Pechuga de pavo", 160, "1 filete"), ("896", "Almendras", 25, "un puñado"),
     CEB_S, AJO, ("2462", "Vino blanco", 40, "un chorro"), ("1630", "Arroz", 60, "en crudo"), AOVE],
    ["Dora las almendras en la sarten y reserva.",
     "Marca el pavo en filetes y reserva.",
     "Pocha la cebolla y el ajo, riega con el vino.",
     "Tritura el sofrito con las almendras y un poco de caldo.",
     "Devuelve el pavo a la salsa 5 min y sirve con arroz."]),
 _r("E100", "Cocido rapido de garbanzos y pollo", "media", 45,
    [("1292", "Garbanzos cocidos", 200, "1 plato"), ("994", "Pechuga de pollo", 120, "1 filete"),
     ("1892", "Zanahoria", 70, "1 unidad"), ("2403", "Patata", 100, "1 pequeña"),
     ("2411", "Puerro", 50, "1/2"), AOVE],
    ["Pon a cocer el pollo con la zanahoria, el puerro y la patata en agua con sal.",
     "Cuece 25 min hasta que todo este tierno.",
     "Añade los garbanzos y calienta 5 min mas.",
     "Sirve el caldo primero y luego los garbanzos con la carne y las verduras."]),
]
